### ISSUE TITLE
Help with mvvm.

### ISSUE THREAD

**Issue by markthuroe** [aritchie/bluetoothle#1]
Hey great work on this plugin and sorry if I'm wasting your time. I downloaded the sample project just to play around with it. I’m having  some trouble  using  acr.mvvm that’s been used in the sample. My trouble is navigating to a new page with mvvm could you give me some help. Using your sample as a base say I add a button to main page or any page at that, how would I set up a command to navigate to a new page/viewmodel? Really would appreciate the help.

**Comment by aritchie** [comment]
no.  the dependencies are marked in the nuget package appropriately
