### ISSUE TITLE
What changes were made from 5.2.0 to 5.2.2

### ISSUE THREAD

**Issue by Zenitram-Oriaj** [aritchie/bluetoothle#101]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Android 7.0

## Version of Library
5.2.2

## Expected Behaviour
?

## Actual Behavior
When upgrading the package from 5.2.0 to 5.2.2, the app crashes before loading the first view. If I downgrade back to 5.2.0, then the app continues to work as expected.

So, I am wanting to know what changes were made between these release versions.

Project type is a Xamarin Forms Shared Code Project.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I don't remember.  Pushing changes and fixes pretty rapidly rightt now.  You can check the commit logs.  All changes are within the last month.  I really only ever support the latest version in any case and 5.3 is out.
