### ISSUE TITLE
Nuget Package not installable

### ISSUE THREAD

**Issue by TobiasDeVries** [aritchie/bluetoothle#102]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [x] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of Library
4.5

## Expected Behaviour
Installation without any errors

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
The installation into the Core PCL project fails with the following error message (loosely translated):

The package "Plugin.BluetoothLE 5.3.1" couldn't be installed. You try to install this package into a project that refers to ".NETPortable,Version=v4.5,Profile=Profile259", however, the package doesn't contain any assemblyreferences oder contentfiles, who are compatible with this framework.

For the android and ios projects the installation succeeds without any errors.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This library is .net standard 2, not pcl which is what you’re trying to install into
