### ISSUE TITLE
Scan for Device Within Certain Range (Like In Feet)

### ISSUE THREAD

**Issue by PapaQuackers** [aritchie/bluetoothle#110]
Hello,

I'm not sure if this is the appropriate place for this question, but I am having an extremely difficult time figuring out how can I scan for devices within a certain range. I'm able to detect and pair with the devices just fine, but for the project I'm working on and want to make it so I can only pair if they're within like 7-10 feet.

**Comment by aritchie** [comment]
I don't generally do support like this, but I have a fair bit of experience with beacons so I'll give you some pointers this round.

Honestly, you're likely not going to get what you're looking for in any sort of precision.  You need to use a combination of the RSSI (which the library provides) combined with a known transmit power (TxPower which is often stripped out of the ad packet especially on iOS).  Generally, if you are in control of the host devices, you can set the txpower to a constant and calculate a guestimate distance from that.  Your best bet is to use something like an ibeacon protocol as that will work properly on iOS, but will give you values like "near", "far", etc.  

If you want to get really advanced, you can get into triangulation metrics, but it now becomes a case of knowing the environment around you as well.

Best of luck
