### ISSUE TITLE
Get Rssi Value of Devices which are not connected

### ISSUE THREAD

**Issue by cunnza** [aritchie/bluetoothle#112]
## Platform

 - Android 7.0 Nougat

## Version of Library
5.3.1

## Expected Behaviour
I get the Rssi When Updated.

## Actual Behavior
I only get Rssi of the Device if I'm connected to that Device.

## Code of Conduct
 _nativeDevice.WhenRssiUpdated(TimeSpan.FromSeconds(3)).Subscribe(rssi => {
                Rssi = rssi;
            });

**Comment by aritchie** [comment]
This is by design.  The vendor Apis get the rssi using the connection.  If you want the rssi for a disconnected device, use the adapter and filter to the deviceid of interest
