### ISSUE TITLE
Characteristic write fails on Samsung devices

### ISSUE THREAD

**Issue by ThiagoAguirre** [aritchie/bluetoothle#117]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Samsung A5 (7.0)

## Version of Library
5.3.1

## Expected Behaviour
Write characteristic

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

I have a function that discovers the available characteristics and save it.
When I try to perform a write in the previous saved characteristic, it fails.(This seems to happen only on Samsung devices. Its working on LG and Motorola devices).

Then I created an Action inside the same function that does the discovery, I call it from from another part of the code

``` csharp
 Write = async (byte[] write) =>
                {
                    await characteristic.Write(write);
                };
```
This "work around" worked on a Galaxy S4 (Android 5.0.1), but not for Galaxy A5(Android 7.0), the code just stops.
This isn't covered by FAQ item "Q. My characteristic read/writes/notifications are not working".

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
There is a deadlock that occurs with samsung queuing mechanism I have.  Give v6.0-beta2 a try.  It has fixes around this.
