### ISSUE TITLE
component not support with .netFramework4.5

### ISSUE THREAD

**Issue by kuropone** [aritchie/bluetoothle#121]
Hi,

Can you update the source so can compatible with .netVersion4.5 ?
I already use your github or from nuget, but it still can't work in .netVersion 4.5

Or, can you tell me which one that should i modified for the upgrade.

Thx

**Comment by aritchie** [comment]
Please don’t delete the issue template in the future.  If you had read it, you’ll notice .net 4.5 isn’t even a support channel
