### ISSUE TITLE
How connect to BLE Peripheral Simulator (https://play.google.com/store/apps/details?id=io.github.webbluetoothcg.bletestperipheral)?

### ISSUE THREAD

**Issue by urmatgit** [aritchie/bluetoothle#125]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [v] iOS
 - [v] Android
 - [] tvOS
 - [] macOS
 - [v] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
android 6.0.1

## Version of Library
6.0.0-beta2

## Expected Behaviour
not connected

## Actual Behavior
connected
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
No offense - this is not a valid use of my time.  I'm not going to code up a walkthrough for you.  There are samples, docs, etc.  If you have a definitive defect, feature request or even something resembling a question that I can answer in 30 seconds that I haven't answered already - I'm happy to help.
