### ISSUE TITLE
[Android] Slow connection to device

### ISSUE THREAD

**Issue by urmatgit** [aritchie/bluetoothle#129]
Hi! can't connect to the device, Run the example and then choose device then click "Connect" and wait a very long time. what was the problem please help.  Other programs BLE scanners connected at once.

 - [] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [x] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Android 6.0.1 (Galaxy S5)

## Version of Library
5.3.1 and 6.0

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I use the gatt autoconnect under the hood which means it will connect to the device when android sees it.  This is usually the preferred behaviour.  You can change this behaviour in the Connect(GattConnectionConfig) to AutoConnect to false to improve this, but you need to ensure the device is nearby

**Comment by urmatgit** [comment]
Thanks for the reply, but I tried all the options GattConnectionConfig AutoConnect and the priority of two devices to be Radom 50cm-10cm does not work

**Comment by aritchie** [comment]
There is nothing more I can do beyond this.  I only know that setting the autoConnect true (default) makes the connection slow.  Setting it to false will make it fast but the device has to be there or it will error.  There is nothing I can do beyond this that I know of

**Comment by urmatgit** [comment]
If I AutoConnect to false do then there is here this error
![photo_2018-02-02_19-35-49](https://user-images.githubusercontent.com/5357178/35744029-4bc2ea9c-0850-11e8-90c7-07e2e559b759.jpg)

**Comment by aritchie** [comment]
You have to catch these errors.  This is an issue with Android that I have tried everything humanly possible to deal with and the fact is that you can only do so much aside from simply trying again
