### ISSUE TITLE
No assembly references for package? .NET 4.5

### ISSUE THREAD

**Issue by Chinmaychafale** [aritchie/bluetoothle#133]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] .NET Standard

## Version of OS(s) listed above with issue
xamarin ios10

## Version of Library

.NET 4.5

## Actual Behavior

I am getting the current error while trying to install the Package to my application build:

Error		Could not install package 'Plugin.BluetoothLE 5.3.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile49', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by aritchie** [comment]
Pcl is not supported.
