### ISSUE TITLE
Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'.

### ISSUE THREAD

**Issue by kikutano** [aritchie/bluetoothle#135]
Hello, I'm trying to install the package 5.3.2 in an Xamarin.Forms Project, but, when i try to install the package from NuGet an error occur:

**_Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author_**.
 
Any Idea? Thanks!

**Comment by aritchie** [comment]
Pcl is not supported
