### ISSUE TITLE
Can't catch Notifications.

### ISSUE THREAD

**Issue by kikutano** [aritchie/bluetoothle#137]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
 - [] Android
 - [] .NET Standard

## Version of OS(s) listed above with issue
6.0.1

## Version of Library
5.3.2
_____
Hi there, I'm trying to read notifications from my BLE, I'm on Android 6.0.1, I can connect to device, I can read the Services and I can find my characteristic. But, when I try to register a notification to read the value of this characteristic, nothing appen:
`public void InitBLE() {
            var scanner = CrossBleAdapter.Current.Scan().Subscribe( scanResult => {

                MyLabel.Text = "Trovato!";

                m_Device = scanResult.Device;

                // Once finding the device/scanresult you want
                m_Device.Connect().Subscribe( connectResult => {

                    var resultConnect = connectResult;

                    //MyLabel.Text = " | Collegato!";

                    m_Device.WhenServiceDiscovered().Subscribe( serviceDiscovered => {
                        IGattService sD = serviceDiscovered;

                        //MyLabel.Text = " | Servizio Trovato: " + sD.Description;

                        Console.WriteLine( sD.Description );

                        if ( sD.Description == "Cycling Speed and Cadence" ) {

                            //IObservable<IGattCharacteristic> cyclingChara = sD.GetKnownCharacteristics( sD.Uuid );

                            sD.WhenCharacteristicDiscovered().Subscribe( charaDiscovered => {

                                IGattCharacteristic cD = charaDiscovered;

                                if ( cD.CanNotify() ) {
                                   
                                    cD.RegisterAndNotify().Subscribe( registerResult => {

                                        CharacteristicResult cR = registerResult;

                                        Console.WriteLine( cR.Characteristic.Description + " " + cR.Data.ToString() );

                                    } );

                                    cD.WhenNotificationReceived().Subscribe( notResult => {

                                        CharacteristicResult cR = notResult;

                                        Console.WriteLine( cR.Characteristic.Description + " " + cR.Data.ToString() );

                                    } );

                                    cD.EnableNotifications( true ).Subscribe( enResult => {

                                        bool bResult = enResult;

                                        cD.RegisterAndNotify( true ).Subscribe( registerResult => {

                                            CharacteristicResult cR = registerResult;

                                            Console.WriteLine( cR.Characteristic.Description + " " + cR.Data.ToString() );

                                        } );

                                        cD.WhenReadOrNotify( new TimeSpan( 0, 0, 1 ) ).Subscribe( notifyResult => {

                                            CharacteristicResult cR = notifyResult;

                                            Console.WriteLine( cR.Characteristic.Description + " " + cR.Data.ToString() );

                                        } );

                                        cD.WhenNotificationReceived().Subscribe( notResult => {

                                            CharacteristicResult cR = notResult;

                                            Console.WriteLine( cR.Characteristic.Description + " " + cR.Data.ToString() );

                                        } );

                                        cD.ReadInterval( new TimeSpan( 0, 0, 1 ) ).Subscribe( readIntResult => {

                                            CharacteristicResult cR = readIntResult;

                                            Console.WriteLine( cR.Characteristic.Description + " " + cR.Data.ToString() );

                                        } );

                                    } );
                                }
                            } );
                        }
                    } );
                } );
            } );     
        }`

Everything works great until _**IGattCharacteristic cD = charaDiscovered;**_. I'm trying in multiple way to catch the notifications without success. **_cD.CanNotify()_** is true. Where I'm wrong? 

Thanks a lot.

**Comment by aritchie** [comment]
Ok - you are calling a bunch of conflicting methods.  You really should take a look at what each of these methods do before simply calling them the way you are.  

WhenReadOrNotify, RegisterAndNotify, and EnableNotifications are all in conflict of each other. 

Also, are your characteristics set with notify or   
```csharp
// you can hook this without being connected
device
.WhenAnyCharacteristicDiscovered
.Where(x => x.CanNotify())
.Select(x =>  x.RegisterOrNotify()) // this enables notifications and returns the observable in 1 call
.Subscribe(...);

device.Connect();
```

Please note that this is not a general support forum.  I supply the code, not much beyond that.
