### ISSUE TITLE
Hi! Can you make it so that you read not only the byte array and another string? advance thanks!

### ISSUE THREAD

**Issue by urmatgit** [aritchie/bluetoothle#140]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [v] iOS
 - [v] Android
 - [] tvOS
 - [] macOS
 - [v] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
all 

## Version of Library
all

## Expected Behaviour

 public override IObservable<CharacteristicGattResult> WhenNotificationReceived()
        {
            this.AssertNotify();

            this.notifyOb = this.notifyOb ?? Observable.Create<CharacteristicGattResult>(ob =>
                this.context
                    .Callbacks
                    .CharacteristicChanged
                    .Where(this.NativeEquals)
                    .Subscribe(args =>
                    {
                        var result = args.IsSuccessful
                            ? this.ToResult(GattEvent.Notification, args.Characteristic.**GetStringValue**())// GetValue())
                            : this.ToResult(GattEvent.NotificationError, "Notification error - " + args.Status.ToString());

                        ob.OnNext(result);
                    })
            )
            .Publish()
            .RefCount();

            return this.notifyOb;
        }
## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

 public override IObservable<CharacteristicGattResult> WhenNotificationReceived()
        {
            this.AssertNotify();

            this.notifyOb = this.notifyOb ?? Observable.Create<CharacteristicGattResult>(ob =>
                this.context
                    .Callbacks
                    .CharacteristicChanged
                    .Where(this.NativeEquals)
                    .Subscribe(args =>
                    {
                        var result = args.IsSuccessful
                            ? this.ToResult(GattEvent.Notification, args.Characteristic.GetValue())
                            : this.ToResult(GattEvent.NotificationError, "Notification error - " + args.Status.ToString());

                        ob.OnNext(result);
                    })
            )
            .Publish()
            .RefCount();

            return this.notifyOb;
        }
## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This will never be put in the library since string usage in ble is rare due to the standard 20 byte limit.

You can do characteristic.WhenNotificationReceived().Select(x => x.Data -> turn into string however you want).Subscribe(...)
