### ISSUE TITLE
Services /Characteristics with 16 bit

### ISSUE THREAD

**Issue by rmenezes** [aritchie/bluetoothle#144]
This is more like a question and not a bug itself. I'm trying to read some services/characteristics that have 16 bit instead of 128 bit. Since GUID has 128 bit, what's the best approach to do this and the library support this?

I'm using the lasted stable version: 5.3.2

Thanks

**Comment by aritchie** [comment]
The code is here for how I manage conversion processes of UUID to GUID:

https://github.com/aritchie/bluetoothle/blob/master/Plugin.BluetoothLE.Android/Extensions.cs
https://github.com/aritchie/bluetoothle/blob/master/Plugin.BluetoothLE.Apple.Shared/Extensions.cs
