### ISSUE TITLE
How to direct connect to service/characteristic with short UUID like 0xFFE0 and 0xFFE1?

### ISSUE THREAD

**Issue by biapar** [aritchie/bluetoothle#150]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

*****
Sorry.
Is't possible to direct connect to characteristic or service by UUID type 0xFFE1 without scan services/characteristics ?
How to convert from UUID 0xFFE1 to long version?
Thanks.

**Comment by aritchie** [comment]
Listen - this is not a support site.  It is for issues and feature requests.  The code is open source.  Look through it and see what I'm doing before just asking for the answers. 

1) Look into GetKnownService and GetKnownCharacteristic.
2) https://github.com/aritchie/bluetoothle/blob/master/Plugin.BluetoothLE.Android/Extensions.cs
