### ISSUE TITLE
UWP

### ISSUE THREAD

**Issue by Rubnyk** [aritchie/bluetoothle#156]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] tvOS
 - [ ] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
UWP

## Version of Library
5.3.4

## Expected Behaviour
CancelConnection() should work ok

## Actual Behavior
When CancelConnection() is called the app throws exception "Collection was modified; enumeration operation may not execute."
only when one the GhatCharataristic notification is enabled (like temperature,accx...)

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
As stated in the issue template, UWP is closed for defects/feature requests.  PR's only please!
