### ISSUE TITLE
Bluetooth 4.2 question

### ISSUE THREAD

**Issue by Uniphix** [aritchie/bluetoothle#162]
This is more of a question on top of this question:

Q. Does this support Bluetooth v2?

No - please read about bluetooth specifications before using this library. LE (Low Energy) is part of the v4.0 specification.

Does this mean this library will not work with v4.2 of Bluetooth?  When I use this framework to connect to our raspberry pi devices I am able to connect just fine on the Raspberry PI 3 Model B which is Bluetooth v4.0 whereas Raspberry PI 3 Model B+ is Bluetooth v4.2.

Would it be that be the issue to why I am struggling to keep a connection to the B+ device?

**Comment by aritchie** [comment]
BLE is part of specification v4.x +

**Comment by Uniphix** [comment]
That is what I thought, thanks!  I am just trying to rule out the issues to why it's not working on the device
