### ISSUE TITLE
Un-Pair a device inside current app

### ISSUE THREAD

**Issue by Markus2807** [aritchie/bluetoothle#165]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue

Unable to un-pair a device ??

I was able to pair my app with my device , but i should be able to break this pairing inside of my app.
Is there a way to do this?

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
No - there isn't.  Android does have a hack which I'm not really interested in implementing as it is an edge case I don't want.
