### ISSUE TITLE
Connect() on Android stuck on Connecting state

### ISSUE THREAD

**Issue by HoekWax** [aritchie/bluetoothle#166]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [*] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Android phone with API 26

## Version of Library
5.3.5

## Expected Behaviour
After connecting to a device, beeing able to discover the services and characteristics

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
My code is working on iOS but on Android, when I connect to a BLE server, the status is updated to "Connecting" and is stuck there.
If I do a PairingRequest the connection is then made and I get the service and characteristic.
I'd like to make it work without a PairingRequest. I used your library on a different project and I managed to do it without. I can't figure out why I can't make it work this time.

Here is my code :

`
            Cleanup.Add(CurrentDevice.Connect(config).Subscribe(x => {
                Logs.DebugLog("Device Connect Worked");
            }));

            Cleanup.Add(CurrentDevice
                    .WhenStatusChanged()
                    .Subscribe(status =>
                    {
                        Logs.DebugLog("Device status changed to " + status.ToString());
                        switch (status)
                        {
                            case ConnectionStatus.Connected:
                                Acr.UserDialogs.UserDialogs.Instance.Alert("Connected", "Connected", "Ok");
                                break;
                            case ConnectionStatus.Disconnected:
                                break;
                            case ConnectionStatus.Connecting:
                                Acr.UserDialogs.UserDialogs.Instance.Toast("Connecting");
                                break;
                            default:
                                break;
                        }
                    })
                );

            Cleanup.Add(CurrentDevice
                            .WhenServiceDiscovered()
                            .Subscribe(service =>
                            {
                                Logs.DebugLog("Discovered Service " + service.Uuid);
                                Cleanup.Add(service
                                    .WhenCharacteristicDiscovered()
                                    .Subscribe(character =>
                                    { // DO STUFF
                                    }));
                            })
                       );`

I also tried with the sample, when I connect it is also stuck on Connecting. It connects only if I pair with the device first.

Do you know what could be the cause of this ?

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by HoekWax** [comment]
By listening to exceptions you mean something like that ? 

`
                Connect = device.Connect(connectionConfig).Catch<object, Exception>(ex =>
                {
                    Logs.DebugLog("EXCEPTION " + ex);
                    return null;
                }) .Subscribe();
`
If yes the code doesn't catch anything.

In the previous app that I made using this plugin I can connect to my BLE server, I can't in this new one.
I use a galaxy s8 and a homtom ht17 Pro.
The server is from [here](https://github.com/androidthings/sample-bluetooth-le-gattserver/blob/master/kotlin/app/src/main/kotlin/com/example/androidthings/gattserver/GattServerActivity.kt), I haven't modified it yet.

The server works on Android with other BLE scanners and on iOS using this plugin.

**Comment by HoekWax** [comment]
I found out the issue.
It works when I explicitly set AutoConnect to false for the GattConnectionConfig.

**Comment by Markus2807** [comment]
Thanks for the information
I had similar problems. On iOS, the connection works very fast and reliable. On Android, the connection was established but stuck in the case connecting to about 30 - 60 seconds.
After setting AutoConnect = false in GattConfig, the connection to Android works immediately.

**Comment by aritchie** [comment]
This is by design with android.  I would suggest leaving it true.  Reconnection and connect when in range is all managed with that flag
