### ISSUE TITLE
Device.CancelConnection() does not work

### ISSUE THREAD

**Issue by mstein11** [aritchie/bluetoothle#169]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Android 6.0

## Version of Library
5.3.5

## Expected Behaviour
Calling Device.CancelConnection() cancels the connection. After a Call to CrossBleAdapter.Current.GetConnectedDevices(); the device should not be returned. The status of the specific device should be disconnecting or disconnected. 

## Actual Behavior
Calling Device.CancelConnection() has no effect. The same device is still returned by CrossBleAdapter.Current.GetConnectedDevices(); and also the status of this device is Connected. Moreover WhenStatusChanged() does not reflect the change.

Further information:

- The device this behavior occurs on is an LG G Stylo. It might well be, that the issue does not occur on other android phones. 

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please note that this issue is related to one that has already been fixed as part of the next version
