### ISSUE TITLE
[Android] WhenKnownCharacteristicsDiscovered not discovering all passed characteristic IDs

### ISSUE THREAD

**Issue by borbmizzet** [aritchie/bluetoothle#177]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [*] Android
 - [] tvOS
 - [] macOS
 - [*] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue

Android 7.0
## Version of Library
6.0.1

## Expected Behaviour
`var dict = await Device.WhenKnownCharacteristicsDiscovered(ServiceID, CharId1, CharId2).ToDictionary(characteristic => Characteristic.Uuid);` results in a dictionary with Count == 2

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
Dictionary.Count == 1.   Remove either CharId parameter and Count still == 1.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
a regression of what defect number?  

WhenKnownCharacteristicsDiscovered is a new extension method that fires with every (re)connection.
