### ISSUE TITLE
RSSI in latest version request

### ISSUE THREAD

**Issue by nexxuno** [aritchie/bluetoothle#179]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of Library
6

Hello, I've updated to the latest version, it works wonders and has some bugfixes I needed. One thing that was removed was important for my project and it is the signal strenght (RSSI). This is not a bug but I'm wondering if you could put that functionality back in the library, with some precautions, like making it oneshot so that people cannot subscribe to it (I understand that you removed it because people misused it).

Thanks.

**Comment by aritchie** [comment]
Was already planning on it.  Added as part of 6.0.3 which should be released later in the week

**Comment by aritchie** [comment]
Throws what - an exception?  Are you connected when you call it?

**Comment by nexxuno** [comment]
Yes.

Sorry the copy paste only copied the first line, this is where I get:

if (this.context.Gatt?.ReadRemoteRssi() ?? false)
ob.OnError(new BleException("Failed to read RSSI"));

If I need to be connected I can try an call ReadRssi() only in the connection callback, the point is that 
WhenReadRssiContinuously
is not returning RSSI either and it should work when the device is connected if I understand that method correctly.

Anyway I'll try and move ReadRssi so that I'm sure it's called only after connection.

Thanks.

**Comment by aritchie** [comment]
That is how WhenReadRssiContinuously works, unfortunately, you didn't give me a any details about what you were using or what your error was.  So ReadRemoteRssi is returning false when connected?  What's the android device/OS version?

**Comment by nexxuno** [comment]
I'm trying to use both the methods cited in my last answer, one throws exception, the other one is not triggering the subscribed method. I'll experiment some more and I'll give you more details. Thanks.
