### ISSUE TITLE
Device not disconnecting on iOS after CancelConnection()

### ISSUE THREAD

**Issue by christiancg** [aritchie/bluetoothle#182]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
11.3.1

## Version of Library
6.0.3

## Expected Behaviour
Device should disconnect when calling IDevice.CancelConnection()

## Actual Behavior
No errors or exceptions are thrown, but the device remains connected. In my case this is very annoying because my app first scans for devices, then the user selects the device and connects to it to do some stuff. As the device is still connected, it will not be found when scanning the second time, so the user cannot see the device after connecting the first time.

If you turn off the bluetooth and on again, the device gets disconnected, and scanning will show again the device.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
If you disable auto reconnection, does the problem go away?  I haven't observed this, but I've had another report of this.

**Comment by christiancg** [comment]
I tried using the following configuration when connecting to a device, but it continues to fail while disconnecting:

toConnect.Connect(new ConnectionConfig
{
	AutoConnect = false,
        AndroidConnectionPriority = ConnectionPriority.High
});

PS: thank you for your work

**Comment by aritchie** [comment]
Are you managing reconnection yourself anywhere?  I thought there may be a race condition of some sort around my auto reconnect, but if you disabled it and it is still happening, there is something external going on.  Are you able to provide a small sample with the issue?

**Comment by christiancg** [comment]
Hi, I don't manage reconnections, as in fact I haven't taken into account that problem (though I should). Maybe the problem is how i'm using the library:

First of all, I scan for bluetooth devices like this:

public void StartScanning()
{
	if (CrossBleAdapter.Current.Status == AdapterStatus.Unsupported || CrossBleAdapter.Current.Status == AdapterStatus.Unauthorized)
		return;
	if (CrossBleAdapter.Current.Status == AdapterStatus.PoweredOn)
	{
		Scan();
	}
	else
	{
		CrossBleAdapter.Current.WhenStatusChanged().Subscribe(newStatus =>
		{
			if (newStatus == AdapterStatus.PoweredOn)
				Scan();
		});
	}
}

private void Scan()
{
	CrossBleAdapter.Current.ScanForUniqueDevices().Subscribe(encontrado =>
	{
		if (encontrado.Name.Contains("indoor"))
			ScanResult.Add(encontrado);
	});
}

ScanResult is an ObservableCollection<IDevice> to which I bind in a listview.

Then the user selects the device from the list and connects to it and the scan is stopped. The scan stops like this:

public void StopScanning()
{
	if (CrossBleAdapter.Current.IsScanning)
		CrossBleAdapter.Current.StopScan();
}

To connect, the next function is called: 

public void Connect(IDevice toConnect)
{
	connectedDevice = toConnect;
	connectedDevice.Connect(new ConnectionConfig
		{
			AutoConnect = false,
			AndroidConnectionPriority = ConnectionPriority.High            
		});
}

The app then opens a new page in which read and writes are made to the connected device (these are working ok, just a little problem when reading long strings of response in some characteristics, but I think that is my fault because not taking into account MTU [in this case, the suscribe to IDevice.ReadCharacteristic is called with Data truncated])

When the user select the option "Exit", the next function is called to disconnect from the device:

public void Disconnect()
{
	if (CrossBleAdapter.Current.IsScanning)
		CrossBleAdapter.Current.StopScan(); //this line is never being called because at this point there is no chance that the adapter is scanning 
	connectedDevice.CancelConnection();
}

Some thoughts: the same IDevice is always being used to read, write, connect and disconnect as I think this is the correct way to do it. It may be plausible that the adapter is still scanning while connecting to the device, because the call to StopScanning() is made in the event OnDisappearing() of the first form, and the connection is made when the user selects the device from the listview

**Comment by aritchie** [comment]
You are certainly doing a bunch of things that aren't necessary.  WhenStatusChanged will ping on the first hook, you don't need to check the status the way you are.  Second, StopScan is considered an emergency break.  You should dispose of the scan itself.  Lastly, Device.ReadCharacteristic will automatically connect if not already connected (though I'm changing this in the next release)
