### ISSUE TITLE
Can't get Rssi

### ISSUE THREAD

**Issue by bluekuen** [aritchie/bluetoothle#187]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Android Version 7

## Version of Library
6.0.3

## Expected Behaviour
Get Rssi

## Actual Behavior
Rssi is never returned from none of the following methods

 //NativeDevice.ReadRssiContinuously(TimeSpan.FromSeconds(1)).Subscribe(rssi =>
                //{
                //    logger.Debug(" ReadRssiContinuously: " + rssi);

                //    Rssi = rssi;
                //});
                //NativeDevice.WhenReadRssiContinuously().Subscribe(rssi =>
                //{
                //    logger.Debug(" WhenReadRssiContinuously: " + rssi);

                //    Rssi = rssi;
                //});
                //rssiUpdateSub = NativeDevice.ReadRssi().Subscribe(rssi =>
                //{
                //    logger.Debug(" ReadRssi: " + rssi);

                //    Rssi = rssi;
                //});
                    NativeDevice.WhenReadRssiContinuously(TimeSpan.FromSeconds(2)).Subscribe(rssi =>
                    {
                        logger.Debug(" WhenReadRssiContinuously: " + rssi);

                        Rssi = rssi;
                    });
                });

**Comment by aritchie** [comment]
Already fixed for next release
