### ISSUE TITLE
ConnectHook does not send notification after reconnection 

### ISSUE THREAD

**Issue by skyvolga** [aritchie/bluetoothle#188]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
IOS 11.3.1

## Version of Library
6.0.3

## Expected Behaviour
Current scenario
1 Connect to a device with the known Id
2 Subscribe to a characteristic with notification by ConnectHook()
4 Simulate reconnection 
5 Device connected and continue to send notifications

## Actual Behavior
1 Connect to a device with the known Id
2 Subscribe to a characteristic with notification by ConnectHook method
4 Simulate reconnection 
5 Device connected but does not continue to send notifications

As a workaround, I removed characteristic.DisableNotifications() in the RegisterAndNotify() and notification started to work properly.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This is fixed in the next release.  Thanks for the report
