### ISSUE TITLE
Method ScanWhenAdapterReady removed - Can't scan with iOS

### ISSUE THREAD

**Issue by louis030195** [aritchie/bluetoothle#190]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS

## Version of OS(s) listed above with issue
10.3.3

## Version of Library
6.0.3

## Problem
I was using ScanWhenAdapterReady on iOS because it need some time to start the adapter,
I updated to the latest version of the bluetooth plugin and saw that this method has been removed, so how are we supposed to scan now ? 
Adding manually a delay before scanning I guess(doesn't work btw System.ArgumentException: Your adapter status is Unknown).
I don't understand why the method has been removed though.

Thank you for your help and great plugin !

**Comment by aritchie** [comment]
The adapter has all of the necessary things you need.  Scanwhenadapterready only chained whenstatuschanged to scan.

The new method you need is scanextra.
