### ISSUE TITLE
Android: Enable Notification Error

### ISSUE THREAD

**Issue by nviswanath24** [aritchie/bluetoothle#196]
Hi,

I'm just using your sample code 'Samples'. When I try to enable the notifications in a characteristic, I get the error below. The example works fine with iOS, I only get the error with Android. (I have tried to test with the SetCharacteristicNotification on Android studio and it works fine with my BLE device. )

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
 - [x] Android

## Version of Library
6.0.3

## Expected Behaviour
Notification should be enabled successfully

## Actual Behavior
"Characteristic Client Configuration Descriptor not found" Plugin.BluetoothLE.BleException

Thanks!

**Comment by nviswanath24** [comment]
The characteristic properties are write and notify. When I tap the characteristic ->tap notify -> HEX/UTF8, the app crashes and the above exception message is displayed. Thanks!

**Comment by aritchie** [comment]
do you have a description of the device?  Maybe from another app?  I have not observed the problem before.

**Comment by nviswanath24** [comment]
Unfortunately I don't. But the app works fine on iOS and I'm only using your sample code. 

 async void ToggleNotify()
        {
            if (this.Characteristic.IsNotifying)
            {
                this.watcher?.Dispose();
                this.IsNotifying = false;
            }
            else
            {
                this.IsNotifying = true;
                var utf8 = await UserDialogs.Instance.ConfirmAsync(
                    "Display Value as UTF8 or HEX?",
                    okText: "UTF8",
                    cancelText: "HEX"
                );
                await this.Characteristic.EnableNotifications(true);
                this.watcher = this.Characteristic
                    .WhenNotificationReceived()
                    .Subscribe(x => UserDialogs.Instance.ConfirmAsync(utf8
                    ? Encoding.UTF8.GetString(x.Data, 0, x.Data.Length)
                                                    : BitConverter.ToString(x.Data))); 
            }
        }

It fails at the EnableNotifications line on Android.

**Comment by aritchie** [comment]
Can you get one?  I’m not worried about the sample.  I want to figure our why your host device is being picked up with a characteristic with notify properties that doesn’t appear to have it.

What version of android are you running and what type of device?

**Comment by nviswanath24** [comment]
I'm running Android 8.1 on a Google Pixel 2. The notification works perfectly on iOS.

**Comment by nviswanath24** [comment]
The same service also has a read, notify characteristic. When I try to enable notification on that it returns this error message - Failed to write descriptor value - WriteNotPermitted

**Comment by aritchie** [comment]
Ok please supply a screenshot from a different app and from the sample.  I can’t help you if I can’t see it.  I don’t have access to your host device.

**Comment by nviswanath24** [comment]
Is there any way that I can edit the plugin and use it only for my project? I want to test and see if the notification works if I use only 'SetCharacteristicNotification' rather than checking for the descriptor. When I just use SetCharacteristicNotification it works on Android Studio. Any indication of how I could proceed would be very helpful. Thanks!

**Comment by aritchie** [comment]
It's open source, you can do whatever you want with it

**Comment by nviswanath24** [comment]
Okay, thank you.
