### ISSUE TITLE
Unauthorized access to "/system/lib/libsqlite.so"

### ISSUE THREAD

**Issue by aalmada** [aritchie/bluetoothle#20]
I get this message with the Samples.Droid on my device with Android 7.0 (Nougat). 

![screenshot_20170224-225544](https://cloud.githubusercontent.com/assets/534533/23324321/e74a68de-fae4-11e6-8e3b-e993938ff6cf.png)

I found this post by James Montemagno but I'm not sure how to contribute to a solution: https://blog.xamarin.com/preparing-for-native-library-linking-changes-in-android-n/

**Comment by aritchie** [comment]
Just ignore it.  It just means the logging functionality isn't working which is changing v2.0 anyhow.  I just have to change it over to sqlite-lite-pcl
