### ISSUE TITLE
Memory usage during a scan

### ISSUE THREAD

**Issue by SamuelLioult** [aritchie/bluetoothle#201]
## Version of OS(s) listed above with issue
Android 6.0.1

## Version of Library
6.0.3

## Expected Behaviour
I expect the memory usage to be stable during a ble scan.

## Actual Behavior
For my use case, I need to scan the devices all through the life cycle of my application. In this case, I find that the use of RAM is constantly increasing. If I stop the scan, it stabilizes but does not become free.

**Comment by aritchie** [comment]
Please don't file such generalistic things like this.  You're asking me to play psyhic here!

What am I fixing?  
How many megs is it using?  
How do you know it is this library?  
How many devices are in range, etc?

You should also get an understanding of/what how I store device scans under the hood.  I keep a log of all seen devices so they can be hooked properly and actually save memory so I don't keep allocating objects per scan.  Scans can be intensive processes in any case.
