### ISSUE TITLE
The ToMacAddress() Extension in Uwp always returns 0

### ISSUE THREAD

**Issue by MKGNZ** [aritchie/bluetoothle#202]
https://github.com/aritchie/bluetoothle/blob/c019be11f935d883bee100eebd7f4027927765fb/Plugin.BluetoothLE/Platforms/Uwp/UwpExtensions.cs#L16

**Comment by MKGNZ** [comment]
Sorry @aritchie I didn't use the form but I just created the issue from the source code.

Thank you for the awesome library !!!!

**Comment by aritchie** [comment]
No worries - the rule only applies to non-contributors.  I'll pump out a patch tonight.  Thanks for letting me know
