### ISSUE TITLE
PauseBeforeServiceDiscovery is not consumed anywhere in the library

### ISSUE THREAD

**Issue by borbmizzet** [aritchie/bluetoothle#203]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [*] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of Library
6.1
## Expected Behaviour
PauseBeforeServiceDiscovery affects app behavior in some way on Android.

## Actual Behavior
There are no consumers of CrossBleAdapter.PauseBeforeServiceDiscovery on Android in the source code.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This is a variable which I haven't decided which I need long term or not.  Please file things that are actually causing issues.
