### ISSUE TITLE
Read Rssi

### ISSUE THREAD

**Issue by bluekuen** [aritchie/bluetoothle#206]
Hallo Ritchie,

can you tell an estimated time when the Rssi feature will be available again ? 
I'm really looking forward to use it in my Application and can't use the Rssi from
the scanResult because i don't get scanResults anymore when i'm connected.

Thank you in advance,
bluekuen

**Comment by aritchie** [comment]
Request for timelines are not welcome here.  Read the issue template (the one you deleted).  If you want something fixed, you can fix it yourself in the future.

In any case, this was out in 6.1
