### ISSUE TITLE
Java.Lang.NoSuchMethodError: no non-static method

### ISSUE THREAD

**Issue by khayalikhopdi** [aritchie/bluetoothle#208]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [YES] Android - Target Version 8.0. Deployed on device with 5.1
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Windows 10 64bit

## Version of Library
Latest cloned from GitHub

## Expected Behaviour
Trying the sample code. Expected the application to run properly

## Actual Behavior

Application gets build and deployed, but throws exception in MainActivity.cs on line#34
 
```
this.RequestPermissions(new []
            {
                Manifest.Permission.AccessCoarseLocation,
                Manifest.Permission.BluetoothPrivileged
            }, 0);

```
Unhandled Exception:

Java.Lang.NoSuchMethodError: no non-static method "Landroid/app/Activity;.requestPermissions([Ljava/lang/String;I)V" occurred

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I don’t test often with anything below android 6 anymore.  You can comment out as necessary

**Comment by khayalikhopdi** [comment]
Thanks, Tested on Android 7.1 device. Worked well.
