### ISSUE TITLE
Handling GATT BleException

### ISSUE THREAD

**Issue by skyvolga** [aritchie/bluetoothle#209]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [*] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue

Android 5.0, 6.0, 6.0.1, 7.0

## Version of Library
6.1.2

## Expected Behaviour

1 Connect to known device
2 Collect data for long period of time

## Actual Behavior
In some cases Library throw an BleException, which I cannot to handle

## StackTrace

```csharp

Plugin.BluetoothLE.BleException: GATT connection could not be established
DeviceContext+<>c__DisplayClass15_0.<Connect>b__0 ()
DeviceContext+<>c__DisplayClass17_0.<InvokeOnMainThread>b__0 (System.Object _)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
RunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)

```

## Code Sample

```csharp
   for (; ; )
            {
                try
                {
                    device = await adapter.GetKnownDevice(Id).FirstAsync();
                    break;
                }
                catch (Exception exception)
                {
                }
            }

   device.ConnectHook(HeartRateService, HeartRateCharacteristic)
                  .Subscribe(characteristic =>
            {
                UnrelatedWork(characteristic);
            }, exception => LogException(exception));
```

Maybe I handle exceptions wrong way, please advice me,

**Comment by aritchie** [comment]
Keep doing what you're doing.  The bug was on the library end.  

However, when the exception does bubble through, you may want to add a retry to the observable to ensure it just keeps trying
