### ISSUE TITLE
UWP COMPATIBILITY

### ISSUE THREAD

**Issue by yiyoMX** [aritchie/bluetoothle#21]
Hi, I just wanted you to know that in the Windows 10 insider compilations the BLE api changed, its still faulty but they are trying to have the same capabilities as Android/IOS.
[More Info here](https://blogs.windows.com/buildingapps/2017/01/13/new-bluetooth-features-in-creators-update-gatt-server-bluetooth-le/#KwH761CvXIawdFMZ.97)
Best regards.

**Comment by aritchie** [comment]
Thanks for the info.  I've been following the updates quite closely.  I've had a look at SDK 15021 and already updated to it on 2.0.  It won't make the release though.
