### ISSUE TITLE
simple BLE scanning using Xamarin.Form

### ISSUE THREAD

**Issue by samosim** [aritchie/bluetoothle#217]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue

Android 8.0

## Version of Library

v6.1.3

## Expected Behaviour
The application was made in Xamarin.Form.  I wanted to make a very simple application in which the user presses to button and see all BLE devices in near vicinity.  In button event handler I wrote:

```
var scanner = CrossBleAdapter.Current.Scan().Subscribe(metod);

public void metod(IScanResult assas) // this metod is outside of event handler
{
    // Debug.WriteLine(assas.AdvertisementData.ManufacturerData.ToString());
}
```
## Actual Behavior
When the button is pressed the following error occurs

onScannerRegistered() - status=0 scannerId=8 mScannerId=0
fail to start le scan - SecurityException thrown: java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
Scan failed, reason: app registration failed

I really do not understand why I got this error because I added in AndroidManifest.xml all needed permissions which are:

```
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />	
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED" />
<uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />
```

I will be appreciated for help 

Best regards

Samo

**Comment by aritchie** [comment]
Please note that this question is outside the scope of this library.  

It is necessary to request certain permissions on newer android versions.  Take a look at the sample launch activity how I deal with this.
