### ISSUE TITLE
Sample Plugin.BluetoothLE

### ISSUE THREAD

**Issue by samosim** [aritchie/bluetoothle#218]
Hi everyone,

I spend a few days to launch the Plugin. BluetoothLE sample but without success. I know that this question is not directly related to BLE library content but I do not know where this question should be better placed.  I downloaded the entire sample to my destop ('C:\Users\samos\Desktop\bluetoothle-master\Plugin.BluetoothLE'). When the sample is launched the following error occurs:

Unable to locate repository containing directory 'C:\Users\samos\Desktop\bluetoothle-master\Plugin.BluetoothLE'. Plugin.BluetoothLE	

I tried to add the library Plugin.BluetoothLE into Xamarin.Form and Android project but I also got the same error. I will appreciate any help.

Best regards
Samo

**Comment by aritchie** [comment]
I have never seen anything remotely close to what you are describing.  I clone the sample and run it all the time without issue.  

I'm sorry, but the question is well outside the scope of the library.
