### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by yiyoMX** [aritchie/bluetoothle#22]
Hi, I have a UWP app, that connects via ble to a custom developed module. Im porting it to Xamarin, Im trying to implement your library, but Im not familiar with reactive programming. Is there any complete implementation example elsewhere? The one included in the readme isnt clear enough.
Thanks in advance!

**Comment by aritchie** [comment]
No idea about other examples.  The sample I have is about as clear as it can get.  I do use some IoC concepts, but if you focus on the actual ble portion, it should be fairly straight forward.

**Comment by yiyoMX** [comment]
Ok, I'll dive into it today. Great job by the way, thanks!

**Comment by yiyoMX** [comment]
You are correct, the examples are very clear, I found that I was missing:

> using System.Reactive.Linq; 

Which translated in an error when trying to await an observable collection.
VS does not recommends it as a solution.
