### ISSUE TITLE
Start up Plugin.BluetootheLE project

### ISSUE THREAD

**Issue by Melitaa** [aritchie/bluetoothle#220]
Hi,

I could not successfully built the samples.Droid program (I just open and built the project). I got the following error
<img width="1069" alt="img" src="https://user-images.githubusercontent.com/42189380/43803443-2768404e-9a99-11e8-932c-6d2738337506.PNG"> If anyone knows what is the reason for this error I I will be grateful for help.

Best regards
Melita

**Comment by aritchie** [comment]
It compiles and deploys fine for me out of master.  Take a look at the build output and see if you are getting some sort of weird error.

You should also make sure you have the latest android sdk stuff.

**Comment by aritchie** [comment]
Also, if you're deploying to an emulator like shown in your screenshot, you won't get very far since it doesn't have emulator bluetooth

**Comment by aritchie** [comment]
No answer - closing
