### ISSUE TITLE
Clear cached BLE device characteristics

### ISSUE THREAD

**Issue by ThiagoAguirre** [aritchie/bluetoothle#226]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
5.0

## Version of Library
6.1.3

## Actual Behavior
I want to perform an OTA firmware updade on a BLE device, during normal operation this device has a name and a set of Services and Characteristics. To perform the OTA, the device reboots and appears with another name and a different set of Services and Characteristis.

I clean all my Characteritics variables, call a dispose on the function that perform Characteristic Discovery and call DisableNotification on the Characteristics. OTA is triggered, the BLE device reboots, WhenStatusChanged notifies the device disconection, the BLE device boots up with another name, WhenStatusChanged notifies the reconnection, but the name and characteristics are the same.( I check with another BLE app that the device is booted on OTA).
If I try to call GetKnownCharacteristics for the new Characteristic that is live on OTA, the function fails an throw an expection on VS:
08-18 09:05:13.303 D/BluetoothGatt(22566): discoverServices() - device: 00:0B:57:86:F3:31
08-18 09:05:13.353 D/BluetoothGatt(22566): onSearchComplete() = Device=00:0B:57:86:F3:31 Status=0

It looks like ther's a cache for the BLE devices. Looking into the manufacturer OTA app, they call this to refresh the device. The app is Android native

```java
private void refreshServices(){
        if (bluetoothGatt != null && bluetoothGatt.getDevice()!=null) {
            refreshDeviceCache(bluetoothGatt);
            bluetoothGatt.discoverServices();
        } else if (service!=null && service.getConnectedGatt()!=null){
            refreshDeviceCache(service.getConnectedGatt());
            service.getConnectedGatt().discoverServices();

/*CALLS A METHOD TO CLEAN DEVICE SERVICES******/
    private boolean refreshDeviceCache(final BluetoothGatt gatt) {
        try {
            Log.d("refreshDevice", "Called");
            Method localMethod = bluetoothGatt.getClass().getMethod("refresh", new Class[0]);
            if (localMethod != null) {
                boolean bool = ((Boolean) localMethod.invoke(bluetoothGatt, new Object[0])).booleanValue();
                Log.d("refreshDevice", "bool: " + bool);
                return bool;
            }
        } catch (Exception localException) {
            Log.e("refreshDevice", "An exception occured while refreshing device");
        }
        return false;
    }
```

So, how to perform the same "cache cleaning" function on this BLE library?

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This was implemented in 6.2 for this exact reason.  Looks like you aren't the only one interested.  This functionality is not enabled by default though.  You have to set before working connecting to a device (perferrably at startup) CrossBleAdapter.AndroidConfig. RefreshServices = true;
