### ISSUE TITLE
"IObservable<IGattServer>" doesn't contain AddService method

### ISSUE THREAD

**Issue by xboundbuild** [aritchie/bluetoothle#228]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Windows 10

## Version of Library
6.2.0

## Expected Behaviour
"IObservable<IGattServer>"  provide AddService method

## Actual Behavior
Doens't provide AddService as documented

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
You have to subscribe or await the CreateGattServer().  

I don't have time to worry about documentation all the time.  You have to be willing to dig into the code occasionally.  Please note that if you don't have a thorough understanding of RX, you will not have success with this library.
