### ISSUE TITLE
Nuget package could not be installed

### ISSUE THREAD

**Issue by SandraHicks** [aritchie/bluetoothle#234]
I have been trying to install version 6.2, 6.13 and 6.12 in my Xamarin Project. Each time I get the error message:
"Could not install package 'Plugin.BluetoothLE 6.1.3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

I tried all different profile options for Version 4.5 and 4.6 and it still gives me the same error message. Which framework versions are supported by this package?

**Comment by aritchie** [comment]
Please look at the readme for supported platforms (https://github.com/aritchie/bluetoothle/blob/master/readme.md).  I don't support .NET framework (any version) or PCL (the Profile111).
