### ISSUE TITLE
[macOS]Is this framework available on macOS platform?

### ISSUE THREAD

**Issue by honbaa** [aritchie/bluetoothle#240]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
 - [] macOS

## Version of OS(s) listed above with issue
MacOS 10.13

## Version of Library
6.1.3

## Expected Behaviour
Help on using this library for macOS development 

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
I saw that version 6.2.1 doesn't include library for MacOS , however version 6.1.3 includes . 
So I used version 6.1.3.
I used below method to scan for devices , however it shows that the adapter state is Unknown.
"CrossBleAdapter.Current.Scan().Subscribe(scanResult => { });"

I can't find any docs for macOS , so could you give me any help?

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I’m sorry - this is not a support form.  I take feature requests and defects with a full repo sample.  I am evaluating cases for paid support in the future.

The source is here along with samples and unit tests.  You simply need to wait for the adapter to be ready for which there is an extension method - ScanExtra.
