### ISSUE TITLE
[iOS] iOS complains that there is no restore identifier

### ISSUE THREAD

**Issue by pravincar** [aritchie/bluetoothle#243]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS

## Version of OS(s) listed above with issue
iOS 12.0

## Version of Library
6.2.1

## Expected Behaviour
I am calling the Init Method in AppDeletegate.FinishedLaunching as shown in the iOS sample project.
````
CrossBleAdapter.Init(BleAdapterConfiguration.DefaultBackgroudingConfig);
````
Since DefaultBackgroudingConfig includes a restore identifier, I expect this enable state restoration.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Console prints the following message after the app has launched
````
API MISUSE: <private> has no restore identifier but the delegate implements the centralManager:willRestoreState: method. Restoring will not be supported
````

**Comment by aritchie** [comment]
Please take some time to review the code before posting what you believe to be a defect.

Init is optional in iOS.  I init a CBPeripheralManager in the static constructor of CrossBleAdapter which runs before Init in case the user doesn't call init at all.
