### ISSUE TITLE
Pairing status on iOS

### ISSUE THREAD

**Issue by gunpuz** [aritchie/bluetoothle#245]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Expected Behaviour

On Android pairing status is represented somewhat right, but on iOS it is showing "PairingStatus.Unavailiable" for device that is actually paired. 
Can't find where it is implemented in this library though.

I assume that it is just default value [here](https://github.com/aritchie/bluetoothle/blob/c019be11f935d883bee100eebd7f4027927765fb/Plugin.BluetoothLE/AbstractDevice.cs#L20)

On Android implementation [here](https://github.com/aritchie/bluetoothle/blob/ed5ba23a9cf091c6687ac2e5fa362e6fc7c7b17e/Plugin.BluetoothLE/Platforms/Android/Device.cs#L186)

Some [help](https://stackoverflow.com/questions/34592179/how-get-the-list-of-paired-bluetooth-devices-in-swift/42085066#42085066)
Some more [help](https://github.com/xabre/xamarin-bluetooth-le/blob/fa8208cbe4113cee5948a4c6dd4812f49df92265/Source/Plugin.BLE.iOS/Adapter.cs#L249)
## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
You cannot get the pairing status on iOS.  The functionality to get connected devices by uuid is in the next release
