### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by pekeboy** [aritchie/bluetoothle#248]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [X] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Expected Behaviour
Trying to install the nuget package. I am using latest Visual Studio Mac. All the other packages are are updated to latest. App working normally I managed to install plugin to iOS and Android packages folder. 

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

This is the error:

Package Plugin.BluetoothLE 6.2.2 is not compatible with portable45-net45+win8+wp8+wpa81 (.NETPortable,Version=v4.5,Profile=Profile259). Package Plugin.BluetoothLE 6.2.2 supports:
  - monoandroid80 (MonoAndroid,Version=v8.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - uap10.0 (UAP,Version=v10.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
Incompatible packages: 1

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
The error you've provided is literally the problem.  The library only supports the frameworks listed.  The library you are trying to install into is a PCL
