### ISSUE TITLE
Open settings on iOS

### ISSUE THREAD

**Issue by gunpuz** [aritchie/bluetoothle#250]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue

IPad 
IPhone 7

## Expected Behaviour

Opens bluetooth settings

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

CanOpenSettings returns false. 

Could have opened something. This code seems to open general settings, better than nothing. [here](https://stackoverflow.com/questions/43752085/prompt-user-to-enable-bluetooth-in-xamarin-forms)
```
// Does not go directly to bluetooth on every OS version though, but opens the Settings on most
    UIApplication.SharedApplication.OpenUrl(new NSUrl("App-Prefs:root=Bluetooth")); 
```
[your code](https://github.com/aritchie/bluetoothle/blob/6eebc72f496e19305bade87b4152c3bab8284221/Plugin.BluetoothLE/Platforms/iOS/Adapter.cs#L46)

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Not interested in doing this.  I'll think about returning a bool in the future.
