### ISSUE TITLE
Adding Request AdvertisingFlags

### ISSUE THREAD

**Issue by Markus2807** [aritchie/bluetoothle#261]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

Dear Aritchie. Thanks for this nice Plugin.

I have a simple addition to your ScanResult.
Within the Bluetooth SIG there are AdvertisingFlags which will let the App know if the currently scanned device is advertising globally or not (LE General Discoverable Mode) and some nice to have information as well.

Is it possible to add these Flags to your current ScanResult struct?

sincerly
Markus

**Comment by aritchie** [comment]
On android, I do supply a lot of the flags.  On iOS, most them are flat out blocked.  Not sure about UWP.
