### ISSUE TITLE
[iOS, Feature] Get MTU size for WriteWithoutResponse

### ISSUE THREAD

**Issue by gunpuz** [aritchie/bluetoothle#269]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

iOS negotiates MTU by itself, so MTU is automatically changed some time. Could you include library check for getting MTU for WithoutResponse type MTU, because it greatly differs for me.

```
var dev = (CoreBluetooth.CBPeripheral)device.NativeDevice;
Debug.WriteLineIf(LogLevelDebug, String.Format("MTU is {0}", device.MtuSize));

mtu = (int)dev.GetMaximumWriteValueLength(CoreBluetooth.CBCharacteristicWriteType.WithResponse);
Debug.WriteLineIf(LogLevelDebug, String.Format("2 MTU is {0}", mtu));

mtu = (int)dev.GetMaximumWriteValueLength(CoreBluetooth.CBCharacteristicWriteType.WithoutResponse);
Debug.WriteLineIf(LogLevelDebug, String.Format("2 MTU is {0}", mtu));
```
This is the output of the commands above. The library is using WithResponse wich differs from WihoutResponse as you can see here
```
[0:] MTU is 512
[0:] 2 MTU is 512
[0:] 2 MTU is 180
```

That would be great for library to include somehow this info, because actually 180 is the real MTU between devices. Other choice is to use native iOS object of course, like i did.
Keep up the good work of your library!

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Will be available in next release
