### ISSUE TITLE
[All platforms] How to cancel timeouts?

### ISSUE THREAD

**Issue by gunpuz** [aritchie/bluetoothle#272]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [*] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

How could one cancel waiting on these observables? Is there any way to cancel them? Seems like device.CancelConnection() is not cancelling them.

For example how to cancel this?
```
await device.DeviceObject.WhenConnected().Take(1).Timeout(Bluetooth.ConnectionTimeout);
```

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please note that this is not a general support form and this question is not related to the BLE library at all.  Please be respectful of this forum and my time.
