### ISSUE TITLE
Cannot access advertising data from ScanForUniqueDevices

### ISSUE THREAD

**Issue by Carbaholic** [aritchie/bluetoothle#283]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Expected Behaviour

I would expect all scans to return the same object and to give access to device advertising data without making a connection.

## Actual Behavior

Some scans return an IScanResult object and others return an IDevice object. As it stands I cannot see a way to scan for unique devices and then decide whether or not to connect to them based on their advertising data. 

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
adapter
            .Scan(config)
            .Distinct(x => x.Device.Uuid)
            .Select(x => x);

**Comment by Carbaholic** [comment]
Thank you!
