### ISSUE TITLE
ConnectHook never returns from LastAsync()

### ISSUE THREAD

**Issue by Carbaholic** [aritchie/bluetoothle#286]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Expected Behaviour
After a notification subscription fires OnCompleted, I would expect an awaiting LastAsync() call to continue.

## Actual Behavior
an awaited LastAsync call never continues, even after a notification subscription fires OnCompleted.

As you can see I subscribe to a characteristic that sends notifications, then I write to a characteristics that sets my peripheral to sending said notifications. I have verified that the OnCompleted event is firing, but the awaiting LastOrDefault() call never completes, it just hangs. 

        `  List<byte[]> history = new List<byte[]>();

            bool isDone = false;
            IObservable<CharacteristicGattResult> historySequence = null;
            IDisposable historySubscription = null;

            try
            {
                historySequence = Peripheral.RPHDevice.ConnectHook(BleService.History, BleCharacteristic.HistoryData);
                int index = 0;
                historySubscription = historySequence.Timeout(TimeSpan.FromSeconds(10))
                                                     .TakeWhile( x => !isDone)
                                                     .Subscribe(
                                                        onNext: Next =>
                                                        {
                                                            history.Add(Next.Data);

                                                            isDone = index++ > 50;
                                                        },
                                                        onError: ex =>
                                                        {
                                                            return;
                                                        },
                                                        onCompleted: () =>
                                                        {
                                                            return;
                                                        });
            }
            catch
            {
                return null;
            }

            try
            {
                await Peripheral.RPHDevice.WriteCharacteristic(BleService.History, BleCharacteristic.HistoryControl, new byte[] { 1 })
                    .Timeout(TimeSpan.FromSeconds(3));
            }
            catch
            {
                return null;
            }

            await historySequence.LastOrDefaultAsync();`

**Comment by Carbaholic** [comment]
Is there a different way to subscribe in your API that will complete? I tried using Enable and disable notifications directly according to the documentation with the same result.

Frankly it seems odd that if I force a sequence to complete using the TakeWhile() function such that it actually enters the OnCompleted block that the stream never completes. I am new to reactive and so I may misunderstand but this seems like the proper way to turn a hot sequence into a cold sequence. Do I misunderstand IObservable sequences or is your implementation different than other reactive implementations? (Not being snarky, I really don’t know and am trying to make sense of all this which is very new to me and very necessary for me to use for my job).

I have a common scenario where I write to one characteristic to make a peripheral do something and then send one or many notifications. I need to subscribe to the notification characteristic, write to the other characteristic and then wait for the notifications to complete; sometimes by sending me data that I can recognize as a completed message and sometimes it just stops sending data. Right now my code is full of “Task.Delay” calls trying to hack around the fact that I don’t know how to await these notifications properly. 

Thank you for your time and your library, I’ve been using it enough that I at least owe you some help with the documentation. 

Eric

**Comment by aritchie** [comment]
Any code you are doing external to the library is a different story.  LastAsync will never return if used directly off of ConnectHook.  There is nothing special about my implementation directly.  You can take a look at the code yourself if you think otherwise.

If you are looking to start an RX/TX setup, ConnectHook likely isn't what you want because it doesn't tell you when the actual characteristic is hooked to send the initial write request.  You are better to discover the characteristics yourself and wire up from there.   

I don't handle support scenarios any longer through github as it is far too time consuming, but I do offer consultancy work if needed.

**Comment by Carbaholic** [comment]
I’ve been looking at the code and I believe you, I just don’t understand react very well and so I can’t tell why LastOrDefaultAsync() would work for one subscription but not another. 

What is your consulting rate and what is your availability? We may be interested in a few hours of help.

Regards,
Eric

**Comment by aritchie** [comment]
Hi Eric

If you email info@bsilabs.ca with your details, one of my colleagues will get you all the info you need.  I have availability towards the middle of next week.  

Allan
