### ISSUE TITLE
[iOS] Adapter cannot be initialized in Foreground mode

### ISSUE THREAD

**Issue by raindeer** [aritchie/bluetoothle#288]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Tested on 11.1, but probably general.

## Version of Library
6.2.3, 6.2.2.
Bug probably introduced on 4 of Oct 2018 in 19dd580e89b5aefca27749cbb01c4f6ff74d9e17

## Expected Behaviour
You should be able to run your app with without BLE background mode on.
If you omit bluetooth-central from you Info.plist you must init the CBCentralManager with RestoreIdentifier = null.
 
## Actual Behavior
All calls to CrossAdapter.Init() results in 
`*** Assertion failure in -[CBCentralManager initWithDelegate:queue:options:]` if bluetooth-central is not in Info.plist.

Im doing:
```
BleAdapterConfiguration adapterconfig = new BleAdapterConfiguration();
adapterconfig.RestoreIdentifier = null;
CrossBleAdapter.Init(adapterconfig);
```
The problem is `RestoreIdentifier = config?.RestoreIdentifier ?? "acrble"` in Apple/AdapterContext.cs
Since a null value will result in RestoreIdentifier="acrble"

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This has been implemented in the replacement library Shiny.BluetoothLE
