### ISSUE TITLE
Max number of characteristics/services

### ISSUE THREAD

**Issue by ThiagoAguirreLorscheiter** [aritchie/bluetoothle#298]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Actual Behavior
There's any limits on the number of characteristcis and/or services a device have for this library to work with. Since we are developing the server part as well, we can arrange the services/charcteristics the best way possible.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
You are better to check the docs for each corresponding OS.  I'm not aware of any constraints, but I've never come close to getting to a place to ask this question
