### ISSUE TITLE
Question on sample App - should I see the Adapter pages on the screen ?

### ISSUE THREAD

**Issue by rogermorrell** [aritchie/bluetoothle#303]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android X
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Visual Studio 17 and 19
android 8
## Version of Library
Current one on GitHub

## Expected Behaviour and Question
Firstly I have to say I tried to run more than  one BTLE Xamarin add on and this is the ONLY one where the sample/example ran !  I appreciate the work done by everyone.

I am new to Xamarin and the example was a bit confusing to me because I was not familiar with Prism and that added an extra layer for me.

This is my question -  In Sample the first part of the App to be invoked is the ADAPTER related pages. I understand that an adapter is needed ! But those pages do not appear to be displayed on the screen.  Should they be ? In seems to go straight into SCAN pages on the screen . I know the ADapter pages are run because I stepped thru with the debugger and the Adapter is found and works because the SCAN finds a number of BT devices .  If the Adapter in the Android device (Lenovo tablet) is turned off I don't see the warning dialog box.

**Comment by aritchie** [comment]
Android & iOS only have one adapter, so the adapter selection screens are not necessary.
