### ISSUE TITLE
Can not discover any device

### ISSUE THREAD

**Issue by bastianbecker21** [aritchie/bluetoothle#306]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] Android

## Version of OS(s) listed above with issue
Android 6.0 & 7.0

## Version of Library
6.2.3

## Expected Behaviour
Discover my devices that I enabled Bluetooth. One is android phone, another one is bluetooth speaker

## Actual Behavior
Discovered nothing

## Code of Conduct
// discover some devices
CrossBleAdapter.Current.Scan().Subscribe(scanResult => {});

**Comment by aritchie** [comment]
You need to give a lot more details than this if you want help!! 

Right now, my guess is that your android device isn’t advertising and your Bluetooth speaker isn’t Bluetooth LE at all since no there isn’t any Bluetooth speakers on the market that are BLE

**Comment by bastianbecker21** [comment]
I am a beginner in bluetooth technology so my comment is not enough to explain about my issue exactly. I got a point from your point, My bluethooth speaker has bluetooth 4.2 but may not be a BLE as you said.
and I am not sure about advertising of my device, How can I make it advertising? thanks for your help

**Comment by aritchie** [comment]
The question goes a bit beyond the nature of a github issue.  You can use the GATT server located in the library to create your own advertising with your mobile device, but for that, I would suggest using the samples and docs to move forward.

Best of luck
