### ISSUE TITLE
GATT Server is not sending response in onDescriptorWriteRequest callback

### ISSUE THREAD

**Issue by mmkrishna2008** [aritchie/bluetoothle#310]
@aritchie It looks like the mGattServer.sendResponse method needs to be called onDescriptorWriteRequest callback when notification enabled on a characteristic. 

I tried the below Sample Android GATT server code with this method implementation and client is not getting 133 error in client side callback onDescriptorWriteResult.

I don't see responseNeeded implemented in this class.
https://github.com/aritchie/bluetoothle/blob/master/Plugin.BluetoothLE/Platforms/Android/Server/Internals/GattServerCallbacks.cs

Which method needs to be implemented in this library to send the response to GATT client to fix this issue?

@Override
        public void onDescriptorWriteRequest(BluetoothDevice device, int requestId, 
BluetoothGattDescriptor descriptor, 
                        boolean preparedWrite, boolean responseNeeded, int offset, byte[] value) {
            Log.d("HELLO", "Our gatt server descriptor was written.");
            super.onDescriptorWriteRequest(device, requestId, descriptor, preparedWrite, responseNeeded, offset, value);
            Log.d("DONE", "Our gatt server descriptor was written.");

            //NOTE: Its important to send response. It expects response else client will disconnect
            if (responseNeeded) {
                mGattServer.sendResponse(device,
                        requestId,
                        BluetoothGatt.GATT_SUCCESS,
                        0,
                        value);

            }
        }

_Originally posted by @mmkrishna2008 in https://github.com/aritchie/bluetoothle/issues/308#issuecomment-494501878_

**Comment by aritchie** [comment]
Please submit a PR - I'm not having this issue

**Comment by mmkrishna2008** [comment]
This is duplicate of #313
