### ISSUE TITLE
Unable to advertise non connectable packets in Plugin.BLE

### ISSUE THREAD

**Issue by mallikarjunpatala** [aritchie/bluetoothle#314]
W e are unable to advertise non connectable packets using Plugin.BLE.

Even set the flag in advertiser 

 "  var settings = new AdvertiseSettings.Builder()
                .SetAdvertiseMode(AdvertiseMode.Balanced)
                .SetConnectable(false);  "  to " false " also not able to make it non connectable.

PFA. In that after making it as non connectable it is showing "Conneectable : Yes" and it is showing the "connect" button beside the device.

Actually result:  it should not show as "Conneectable : Yes" and "Connect"
![noncon2](https://user-images.githubusercontent.com/40006543/59594670-e55c1700-9111-11e9-9a9b-25bdf065ec45.PNG)
 button

Is there any flags that we need to change along with this.

Please kindly help us to resolve this issue.
@aritchie 
![noncon2](https://user-images.githubusercontent.com/40006543/59594268-299ae780-9111-11e9-8327-91d3aa5169f6.PNG)
![Noncon1](https://user-images.githubusercontent.com/40006543/59594271-299ae780-9111-11e9-9d5a-99b6a8b30f3a.PNG)

**Comment by aritchie** [comment]
@mallikarjunpatala Please note that this is not technical support forums.  I also only give out direct lines of communication for paid engagements.  If you look at the AdvertisementData in the StartAdvertising call, there is nothing that allows you to control that flag which is intentional since iOS doesn't let you control it.

**Comment by aritchie** [comment]
This has been answered.  Please don’t send multiple communications on other channels.  If the library doesn’t do what you need it to do, please submit aPR.  this isn’t a bug.  It just isn’t something I implement
