### ISSUE TITLE
Not able to advertise 16bit UUID in xamarin forms on ios.

### ISSUE THREAD

**Issue by mallikarjunpatala** [aritchie/bluetoothle#316]
We are using Plugin.BLE in xamarin forms to advertise data. In advertising data we are sending the Local name and Service UUID's as  :

string UUID = "4d78**52c8**-6fd8-11e9-a923-1681be663d3e";
var guid1 = new Guid("000055A2-0000-1000-8000-00805F9B34FB");
var guid2 = new Guid("000052C8-0000-1000-8000-00805F9B34FB");
CrossBleAdapter.Current.Advertiser.Start(
				new AdvertisementData
				{
					LocalName = "Test",
					ServiceUuids = new List<Guid> { guid1, guid2 }
				});

We used this ""0000XXXX-0000-1000-8000-00805F9B34FB""  to convert 128 bit UUID to 16 bit.
And in the place of XXXX we used our UUID "52c8"
It is converting to 16 bit properly in Android but It is not converting in IOS. 

PFA Android and IOS. In IOS it is showing as incomplete list of 128 bit Service UUID's.

![Capture16bit](https://user-images.githubusercontent.com/40006543/59769143-28112100-92c3-11e9-8ec6-97e1c6f782d3.PNG)
![Noncon1](https://user-images.githubusercontent.com/40006543/59769145-28112100-92c3-11e9-8881-e8a20cd0f889.PNG)

Can someone please guide us to resolve this issue.

**Comment by aritchie** [comment]
I'm not doing anything special with the CBUUIDs under the hood.  I would take a look at the code and google a bit to see what may be going on.  I'm happy to fix if you find something useful.

Also - PLEASE USE THE ISSUE TEMPLATE.  Everyone else has too, so I can get all of the upfront questions out of the way and others can search the issues appropriately.
