### ISSUE TITLE
Galaxy S4 - GATT Server Advertizement issue

### ISSUE THREAD

**Issue by mmkrishna2008** [aritchie/bluetoothle#317]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [-] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Android 5.1

## Version of Library
6.2.4

## Expected Behaviour

The adapter should return GATT Server is not supported on Galaxy S4 as this device do not have Bluetooth LE advertizing support.

## Actual Behavior
The library assumes all the devices running above API level 21 have Gatt Server Support. While starting the advertizement on Galaxy S4 the app is getting crashed.

In addition to API level 21 check, the below check needs to be implemented to verify the device has advertizing support is available.

`
Android - Java

BluetoothLeAdvertiser advertiser = BluetoothAdapter.getDefaultAdapter().getBluetoothLeAdvertiser(); or
BluetoothAdapter.getDefaultAdapter().isMultipleAdvertisementSupported()
`
## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This was fixed in the last release
