### ISSUE TITLE
[Update Notes] Update Notes for updates of the Plugin

### ISSUE THREAD

**Issue by bluekuen** [aritchie/bluetoothle#320]
Hey,
is it possible to show some Update Notes anywhere ? 
I really would like to know what has been improved or fixed but could't
find any overview. 
Nevertheless, thanks for this great Plugin!

**Comment by aritchie** [comment]
There is a changelog https://github.com/aritchie/bluetoothle/blob/master/docs/changelog.md

You can also always review commits.

**Comment by bluekuen** [comment]
Ah nice, thank you very much!! That's what i was looking for :)
