### ISSUE TITLE
[Bug] Disconnecton App exit

### ISSUE THREAD

**Issue by bluekuen** [aritchie/bluetoothle#322]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
newest
## Version of OS(s) listed above with issue
iOS

## Steps to Reproduce
1.Connect to a Ble Device 
2. Force Close the App
3. Device is still connected

## Expected Behavior
Device gets disconnected.

## Actual Behavior
Device is still connected.

I don't know if this is a bug or if iOS does it by design but i need to disconnect the Device if the 
App closes. I want to allow that the App stays connected to the Devices if in Background but on App exit i want my Devices to get Disconnected like on Android. How could i do that? 
Any Help is appreciated!

**Comment by aritchie** [comment]
https://github.com/aritchie/bluetoothle/blob/master/docs/device.md This is documented.  You can call device.CancelConnection to stop the connections.
