### ISSUE TITLE
[Question] Scanning for devices with particular manufacture data

### ISSUE THREAD

**Issue by nabin21** [aritchie/bluetoothle#326]
Current ScanConfig class has a service uuids as a filter. How can i filter scan for a particular manufacture data?

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP
 - [x] .NET Standard

## Steps to Reproduce
1.
2.
3.

## Expected Behavior
ScanConfig with filter for manufacture data 

## Actual Behavior
ScanConfig has only serviceuuids as filter

**Comment by aritchie** [comment]
Please respect the policies around the issue templates.  They are there for a reason!! 

I'll answer this time around, but the code is open - you should take the time to read it for yourself.
This project uses Reactive Extensions so you can can filter using the Where clause off of scan.  The scanconfig is used mostly for background scanning as it allows the OS to manage the filtering.  I only expose what the OS allows in the config.
