### ISSUE TITLE
[Bug] iOS 13 CrossBleAdapter.Current.Status Unknown

### ISSUE THREAD

**Issue by zxcvbinz** [aritchie/bluetoothle#328]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
6.2.6
## Version of OS(s) listed above with issue
iOS 13 beta 4

## Steps to Reproduce

1. Bluetooth ON
2. CrossBleAdapter.Current.WhenStatusChanged().Subscribe(status => {}) 
3. var status = CrossBleAdapter.Current.Status;

## Expected Behavior
CrossBleAdapter.Current.Status = PoweredOn

## Actual Behavior
CrossBleAdapter.Current.Status = Unknown

**Comment by aritchie** [comment]
I don’t support beta OS releases
