### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by saadsaifse** [aritchie/bluetoothle#333]
## Code understanding
`CrossBleAdapter` is a partial static class that has a property of `IAdapter` with the name of `Current`. This gets initialized from the constructors of partial `CrossBleAdapter` classes. For example, in Apple folder

```
    public static partial class CrossBleAdapter
    {
        static CrossBleAdapter()
        {
            Current = new Adapter();
#if __MACOS__
            AdapterScanner = new AdapterScanner();
#else
            AdapterScanner = new NotSupportedAdapterScanner();
#endif
        }
...
``` 

and in Tizen, it goes like below 

```
    public static partial class CrossBleAdapter
    {
        static CrossBleAdapter()
        {
            AdapterScanner = new AdapterScanner();
            Current = new Adapter();
        }
    }
```

I have two questions here:

1. All `Adapter` classes have same namespace `Plugin.BluetoothLE` and not all are `partial`. Why the compiler is not complaining about that? 

2. According to the platform, how the right `Adapter` gets initialized? It seems like all adapters would get initialized this way :/

Despite the complier giving me red underlined errors, the library compiles on VS for Mac and Rider IDE.

I know this is quite basic but I am having a hard time understanding what is going on here.

**Comment by aritchie** [comment]
> All Adapter classes have same namespace Plugin.BluetoothLE and not all are partial. Why the compiler is not complaining about that?

It is a multitargeted library, so it is compiling the same project (each time per platform I define) and only including folders that are defined per platform.  Take a look at Plugin.BluetoothLE.csproj to get a better idea.  There is also a few good blog posts out there - https://www.bugsnag.com/blog/building-multi-targeted-dot-net-libraries

> According to the platform, how the right Adapter gets initialized? It seems like all adapters would get initialized this way :/

As soon as you call CrossBleAdapter.Current, the static constructor for the platform lib is called.

> Despite the complier giving me red underlined errors, the library compiles on VS for Mac and Rider IDE.

VS4Mac does not support multitargeting yet.  You need to use VS4win to compile things properly.
