### ISSUE TITLE
[Bug]  Error on adding package: Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `System.Reactive`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `System.Reactive`.	

### ISSUE THREAD

**Issue by KRA2008** [aritchie/bluetoothle#336]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [x] .NET Standard

## Version of Library
6.26
## Version of OS(s) listed above with issue
n/a

## Steps to Reproduce
1. Create new app
2. Add Nuget Package
3. Try to build/deploy

## Expected Behavior
Should build/deploy

## Actual Behavior
Get error: Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `System.Reactive`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `System.Reactive`.	

ALSO, proceeding with adding the nuget package and assembly reference as suggested does not help.

**Comment by aritchie** [comment]
Please do a search on closed issues.  I have answered this so many times.

**Comment by KRA2008** [comment]
Ok, thank you. Switching to VS2019 fixed it for me.
