### ISSUE TITLE
Unable to read data in read characteristics

### ISSUE THREAD

**Issue by suriyaKalidoss21** [aritchie/bluetoothle#339]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
 6.2.6
## Version of OS(s) listed above with issue
iOS 11.0

## Steps to Reproduce
1. In the attached sample Write the data to the Bluetooth device
2. After writing data to write characteristic, I can't able to read data
3. Read data not updated

## Expected Behavior
   Should able to read data in read characteristic

## Actual Behavior
   data not found in read characteristic
[testsample.zip](https://github.com/aritchie/bluetoothle/files/3616485/testsample.zip)

**Comment by aritchie** [comment]
Ok - that's enough!  I've answered this question on your forum post.  THIS IS NOT A DEFECT.  You aren't even reading data - you are requesting notifications.  Do it before your write!!
