### ISSUE TITLE
Unable to read data after write

### ISSUE THREAD

**Issue by suriyaKalidoss21** [aritchie/bluetoothle#340]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
 6.2.6
## Version of OS(s) listed above with issue
iOS 11.0

## Steps to Reproduce
1. Enable notification called before the write 
2. Write the data to the Bluetooth device
3. unable to Read characteristic

## Expected Behavior
   Should able to read data in read characteristic

## Actual Behavior
   data not found in read characteristic
Attached code:  

         readcharecters.EnableNotifications(true);

                readcharecters.WhenNotificationReceived().Subscribe(result => {

                    var test = result.Data; value not obtained

                });
            }
            if (selectedCharacteristic.CanWrite())
            {
                WriteCharacteristicAsync(selectedCharacteristic);
            }
        private async void  WriteCharacteristicAsync(IGattCharacteristic characteristic)
        {
                string writetest = "LIST_DIR,audio";
                byte[] bytes = Encoding.ASCII.GetBytes(writetest);
               await characteristic.Write(bytes);
                await Task.Delay(4000);
         }

**Comment by suriyaKalidoss21** [comment]
I also tried to read after write but my characteristic '6e400003-b5a3-f393-e0a9-e50e24dcca9e' does not support reads

**Comment by suriyaKalidoss21** [comment]
Please provide me the solution

**Comment by suriyaKalidoss123** [comment]
Hi @aritchie ,
  Could you please provide some solution

**Comment by aritchie** [comment]
This is extremely poor behavior.  Don't spam me, I don't work for you!  I've supplied a library that you can use for free.  I've already told you, I'm not tech support.  I did supply you with an answer how to solve the question you were asking, it just wasn't what you needed for the device by the sounds of it.  I also notice you are spamming other projects for answers so someone can figure this out for you:

https://github.com/xabre/xamarin-bluetooth-le/issues/384
https://github.com/xabre/xamarin-bluetooth-le/issues/379

The fact is, no one knows your BLE device.  These libraries are likely working fine with said device, but you aren't adhering to how you should interact with that device.
