### ISSUE TITLE
[Bug] Can't WRITE

### ISSUE THREAD

**Issue by sesitosvdx** [aritchie/bluetoothle#350]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
6.2.6
## Version of OS(s) listed above with issue
Android

## Steps to Reproduce
I'm able to connect but I can't WRITE any value. I know it because I can debug my BLE chip and I can see that I get connected, but I can't write anything. This is my code (with both methods to write):

this.ConnectedDevice.WhenAnyCharacteristicDiscovered().Subscribe(cha =>
            {
                cha.WriteWithoutResponse(valuesToSend);
                cha.Write(valuesToSend);
            });

## Expected Behavior
Expected to be writing, and that I can see values get written when debuggind the BLE chip.

## Actual Behavior
It connect with BLE, but can't Write anything.

**Comment by aritchie** [comment]
You need to supply a reproducible case with a factual defect.  This is not a support forum!

Your code is doing several things wrong anyhow
1) You are blind writing to all characteristics and likely getting errors which you aren't managing
2) Write & WriteWithoutResponse are observables.  The fact that you aren't subscribing to them or awaiting to them means they aren't even being triggered.
