### ISSUE TITLE
Referencing source code of plugin raises exception "No platform plugin found. Did you install the nuget package in your app project as well?"

### ISSUE THREAD

**Issue by roiko** [aritchie/bluetoothle#351]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [X] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library

commit 1d098d8ef08af1f8fb8bde61cbb1427cf931bf4b on branch 6.3.0

## Version of OS(s) listed above with issue

Android 9.0

## Steps to Reproduce
1. Clone the git repository and move on branch 6.3.0
2. Remove not used target information from csproj (monoandroid81;monoandroid90;xamarinios10;xamarinmac20;xamarin.TVOS10)
3. Reference the bluetooth LE project from a Xamarin.Forms project
4. Call CrossBleAdapter.Current
## Expected Behavior

Both AdapterScanner and Current are not null

## Actual Behavior
AdapterScanner and Current are null and the following exception is raised: "No platform plugin found. Did you install the nuget package in your app project as well?"

When I use the nuget package no exceptions are raised the adapter is correctly managed. I can perform scan operations without any issue or exception.
Now I need to check some features available on branch 6.3.0, but I'm not able to use it. 

Do I have to do some extra steps not written here [link](https://github.com/aritchie/bluetoothle#setup) ?
I cannot understand how the plugin is initialized, can initialization be the cause of the problem?

**NOTE**: Since my Xamarin.Forms app is .netstandard2.0, I removed the following lines from csproj file in order to avoid build errors on platforms I don't use:

```
<TargetFrameworks>netstandard2.0;monoandroid81;monoandroid90;xamarinios10;xamarinmac20;xamarin.TVOS10</TargetFrameworks>
<TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">uap10.0.16299;$(TargetFrameworks)</TargetFrameworks>
```

and replaced them with:
`<TargetFrameworks>netstandard2.0</TargetFrameworks>`

In MainActivity.cs I'm requesting bluetooth access in this way:
```
System.String permission = Manifest.Permission.AccessFineLocation;

if (ContextCompat.CheckSelfPermission(this, permission) != Permission.Granted)
{
	ActivityCompat.RequestPermissions(this, new System.String[] { Manifest.Permission.AccessCoarseLocation, Manifest.Permission.AccessFineLocation }, 0);
}
else
{
	System.Diagnostics.Debug.WriteLine("Permission Granted!!!");
}
```

**Comment by aritchie** [comment]
I'm sorry - this isn't the type of request I'm willing to walk you through.  This is a multitargeted library.  Nuget manages the implementation that is used based on the compile target.  You can find some documents out there on this.
