### ISSUE TITLE
Restricting the BLE peripheral device to connect to only one Master

### ISSUE THREAD

**Issue by AnithaRaniT** [aritchie/bluetoothle#357]
Hi,

I have created a peripheral application in Xamarin forms using BluetoothLE. 

I want to restrict my BLE Peripheral device to connect with only one master at a time always .IF i receive a connection request from some other master/central device, it should reject the connection request ! 

 - [x] iOS - Iphone8, Iphone8plus,IphoneX
 - [x] Android- All the versions above 8

## Feature Library

 - [x] BluetoothLE

## Version of OS(s) listed above with issue
Both Android and IOS have the same issue

## Steps to Reproduce
1.Create Peripheral Application
2.Advertise packets (Connectable)
3.Central (Master) will get connect
4. Data exchange is happening between them contineously
5. Scan with another central
6.Connect from another central
7.It gets connect
8.Send some data from newly connectly Central
9. The data transfer between Firstly connected central got interuppted

## Expected Behavior
When any request received from new central it should not accept, it should reject if it is already connected to the central and the connection is in active

## Actual Behavior
Peripheral is connecting to the multiple centrals hence data exchange between the first connected central is getting disturbed. It should not happen.

Please anyone have any idea how to restrict multiple connections please help me to fix it.

Thanks in Advance.

**Comment by aritchie** [comment]
This is the behaviour of the platform.  You are welcome to send a PR for this, but this isn't something I'll be doing.
