### ISSUE TITLE
Write Characteristic a Large Byte Array Failed to Send [Bug] 

### ISSUE THREAD

**Issue by kebaranas** [aritchie/bluetoothle#369]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
Latest Version
## Version of OS(s) listed above with issue
Android 7.0

## Steps to Reproduce
1. Client mode.
2. Use Device.WriteCharacteristic() method.
3. Write characteristic a large byte array.

## Expected Behavior
Receive the large byte array from the phone to the Arduino serial monitor.

## Actual Behavior
Got a BleException with a message:
[0:] Message: Failed to write characteristic - 9
[0:] Source: mscorlib

**Comment by aritchie** [comment]
You can't write a value larger than the MTU.
