### ISSUE TITLE
TCP/IP over PAN

### ISSUE THREAD

**Issue by benlemond** [aritchie/bluetoothle#371]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Does this library support TCP/IP/Socket traffic over PAN (personal area network)? I'm looking for a method to control a Raspberry Pi (running bluez protocol) using ZMQ and json.

I would like to do this over TCP/IP over Bluetooth if possible.

## API Changes
unsure

## Intended Use Case
Use TCP/IP socket protocols over a bluetooth PAN

**Comment by aritchie** [comment]
This plugin is for Bluetoothle (hence the name), which has nothing to do with PAN setups
