### ISSUE TITLE
Under "Setup", plz change the "Acr.BLE" to "Plugin.BluetoothLE", otherwise it may lead to some confusion between the two package version, especially since your intro recommends uninstalling Acr.BLE for the newer Plugin.BluetoothLE

### ISSUE THREAD

**Issue by wrt** [aritchie/bluetoothle#38]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] tvOS
 - [] macOS
 - [] PCL

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible
Contact GitHub

**Comment by aritchie** [comment]
Please submit PR's for documentation request changes in the future
