### ISSUE TITLE
When is version 2 or a beta -- need UWP Windows 10 Phone

### ISSUE THREAD

**Issue by hubert-associates** [aritchie/bluetoothle#4]
Nice. Thanks. When is version 2 -- need UWP Windows 10 Phone. I see an UWP sample? ... I'll take a look.

**Comment by hubert-associates** [comment]
Thanks. Not expecting a real timeline, just wondering. I've got the UWP Windows 10 Phone sample running -- or most of it -- now. I noticed that if one starts the samples on a machine without a bluetooth adapter that it crashes with null pointer exceptions in a few places. I'll see what I can do, but I'm still getting familiar with this. No timelines :-)

**Comment by SoyPan** [comment]
Apparently they just updated the SDK (build 15003 and higher) with new APIs that should help you solve most of the problems and ugly workarounds with UWP and BLE. 

http://aka.ms/bluetoothgatt
