### ISSUE TITLE
UWP Ready?

### ISSUE THREAD

**Issue by vbisbest** [aritchie/bluetoothle#40]
Is UWP ready.  I just gave it a try and I am getting "No Platform target found".  I do have the plugin installed under UWP.

**Comment by aritchie** [comment]
It would be advertised in the readme if it was

**Comment by chandrakantnitt** [comment]
Sorry to bug you @aritchie but do you have an ETA for this?

**Comment by aritchie** [comment]
@chandrakantnitt That depends... how's your PR for it coming?
