### ISSUE TITLE
No platform plugin found.

### ISSUE THREAD

**Issue by SoyPan** [aritchie/bluetoothle#44]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [x] UWP
 - [] tvOS
 - [] macOS
 - [] PCL

## Version of OS(s) listed above with issue
1703 Build 15063.296

## Version of Library
3.1.0

## Expected Behaviour
Get a "true" for `CrossBleAdapter.AdapterScanner.IsSupported` for UWP.

## Actual Behavior

> System.ArgumentException occurred
>   HResult=0x80070057
>   Message=[Plugin.BluetoothLE] No platform plugin found.  Did you install the nuget package in your app project as well?
>   Source=<Cannot evaluate the exception source>
>   StackTrace:
>    at Plugin.BluetoothLE.CrossBleAdapter.get_AdapterScanner()
>    at PLT_Universal.FirstConnectionScreen.<<-ctor>b__2_1>d.MoveNext() in D:\VS Projects\PLT-Uni\PLT Universal\PLT_Universal\FirstConnectionScreen.xaml.cs:line 45
> 
This happens at the following line:
```cs
Debug.WriteLine("Adapter Scanner supported: " + CrossBleAdapter.AdapterScanner.IsSupported);
```
 in my PCL. I tried unistalling the app from the device -> cleaning -> erasing bin and obj folders -> reinstalling the plugin in my PCL and UWP project to no avail.

I ran the UWP sample and everything works fine, am I missing an initialization somewhere? Thanks!

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible
Contact GitHub

**Comment by aritchie** [comment]
UWP comes with zero support during the beta period.  I am only taking PRs for it.  It hasn't even been deployed to nuget yet and was intended for private testing for the next few days.

Actually, you were the one I already told in the commit message that I wasn't supporting anything in the meantime.... come on dude!!
