### ISSUE TITLE
Not able to send data over iOS

### ISSUE THREAD

**Issue by Larka2** [aritchie/bluetoothle#49]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] PCL
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
iOS 9.3.5
Android API 23
## Version of Library
3.1.1.

## Expected Behaviour
I want to send some data to my BLE Device.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
I use the following code for sending some data:
```
public static void WriteDataToBle(IGattCharacteristic c, int value)
		{
	    	byte[] data = new byte[4];
			data[3] = (byte)(value >> 24);
			data[2] = (byte)(value >> 16);
			data[1] = (byte)(value >> 8);
			data[0] = (byte)(value);
			System.Diagnostics.Debug.WriteLine($"**** Writing to Ble: {value}");
			if (c.CanWriteWithoutResponse())
			{
				System.Diagnostics.Debug.WriteLine("**** Writing to Ble CanWriteWithoutResponse");
				c.WriteWithoutResponse(data);
			}
			else
			{
				if (c.CanWriteWithResponse())
				{
					System.Diagnostics.Debug.WriteLine("**** Writing to Ble CanWriteWithResponse");
                    c.Write(data);
				}
				else
				{
					if (c.CanWrite())
					{
						System.Diagnostics.Debug.WriteLine("**** Writing to Ble CanWrite");
						c.Write(data);
					}
					else
					{
						System.Diagnostics.Debug.WriteLine("**** Writing to Ble ????");
					}
				}
			}
		}
```

And I use this call for the function
WriteDataToBle(TheCharacteristicForReceiving, data);

I am connected with my BLE-Device by ZOC. But I can´t see my received data. 
When I use a BLE Scanner App and I send my Data with this App I can see my send data over ZOC. 
I do not know which part of sending I am doing wrong.
I wrote the my hole code with the iOS specific library and there was no problem. But I want use the code for Android to. So I decide to use your Plugin. But I can't get it work.
I hope you can help me

**Comment by aritchie** [comment]
When you call c.Write, you need to either await or subscribe to the call.  This library uses reactive extensions.  I would suggest reading up on them before getting to in depth with this library
