### ISSUE TITLE
List of available devices and connection.

### ISSUE THREAD

**Issue by ToKoAFC** [aritchie/bluetoothle#50]
Hi, I don't understand your documentation.
Would you be so kind and tell me, how can I get a list of available devices?
How to connect and send some data?

I want to send some data from android to another bluetooth module.
Which methods I supposed to use?

**Comment by aritchie** [comment]
The very first portion of the readme shows the client basics for exactly what you're asking.  There is also a complete end-to-end sample located within this repo.
