### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by StefaanAvonds** [aritchie/bluetoothle#53]
When updating the PCL to target .NET Standard 1.4, Xamarin automatically adds 'System.Reactive.Core' with version 3.1.1 to the project. However your Bluetooth-plugin uses version 2.2.5 and thus generates errors since multiple versions are installed:

```
The call is ambiguous between the following methods or properties: 'System.ObservableExtensions.Subscribe<T>(System.IObservable<T>, System.Action<T>)' and 'System.ObservableExtensions.Subscribe<T>(System.IObservable<T>, System.Action<T>)'

The type 'ObservableExtensions' exists in both 'System.Reactive.Core, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

Is it possible to update the reactive-reference? Or is it possible to redirect to a specific version of this assembly?  Adding an entry to "app.config" didn't help, as they said on [StackOverflow](https://stackoverflow.com/questions/31255666/how-do-i-redirect-assembly-binding-to-the-current-version-or-higher).

Thanks in advance!

**Comment by aritchie** [comment]
Updating PCL to netstandard will not automatically add RX 3.1.1.  You've updated it via nuget somewhere along the line.  This was/is a large problem with the RX releases in my opinion.  

The current version of this plugin does currently is not netstandard or rx 3.1.1 ready.  The next release (v4) which is almost ready will
