### ISSUE TITLE
iTAG connection

### ISSUE THREAD

**Issue by Enoges** [aritchie/bluetoothle#55]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [*] Android

## Version of OS(s) listed above with issue
Android 4+ & iOS 9+

## Version of Library
3.1.1

## Expected Behaviour
Receive byte from iTAG when I push the butom

## Problem
Hi, I know here isn't the site to post it. But I don't know where I can ask it.
I have a Bluetooth LE iTAG with a button. This button send a list of bytes whe it clicked.
My problem becomes when I try to use your plugin  to do it.
Who is the correct way to : 
1. Detect the device.
2. Connect to device.
3. Wait to receive data.
4. If I receive data make something.

Im so sorry to post that in issues, but I really need to solve my problem.

Thanks a lot.

**Comment by aritchie** [comment]
You should probably read about Bluetooth LE before you get too far into your project.  The way of doing things really depend on your device.  Points 3 and 4 are missing points like discovering services/characteristics.  If a button is being pressed to send data, you are likely hooking up to characteristic notifications.  

All of the necessary functions should be available and documented within this library to assist with your project.

Best of luck.
