### ISSUE TITLE
Extensions_Adapter.cs

### ISSUE THREAD

**Issue by rlingineni** [aritchie/bluetoothle#57]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] PCL
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of Library
3.1.1

## Expected Behaviour
ScanWhenAdapterReady(); should continue as a normal scan. Disposing it should stop the scan in progress.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
Scanning is not actually stopped when Disposed, when the `ScanWhenAdapterReady();` is used to begin a scan. Throws error message when my scan pages opens a second time `An existing scan is in progress`. Normal `Scan` operation works fine

**Comment by aritchie** [comment]
I ran some tests with it and it worked just fine.  Please provide a test sample with showing the issue

**Comment by aritchie** [comment]
No reply - closing
