### ISSUE TITLE
Restore package: reactiveui 7.5.0-alpha0027 

### ISSUE THREAD

**Issue by bodeg** [aritchie/bluetoothle#59]
Hi.
I download the BluetoothLE brunch, and tried to build it.
For some reason, I cannot restore the reactiveui package. 
I think it is used by the sample projects

An error occurred while trying to restore packages:
Unable to find version '7.5.0-alpha0027' of package 'reactiveui'.
C:\Program Files(x86)\Microsoft SDKs\NuGetPacakages\: Package 'reactiveui.7.5.0-alpha0027' is not found on source 'C:\Program Files(x86)\Microsoft SDKs\NuGetPacakages\.
https://api.nuget.org/v3/index.json: Package  'reactiveui.7.5.0-alpha0027' is not found  on source 'https://api.nuget.org/v3/index.json'.

With Regards.
alon

**Comment by aritchie** [comment]
Because this project is .net standard, I used a .netstandard version of reactiveui which has not been released.  You can get it from their nuget server - https://www.myget.org/F/reactiveui/api/v3/index.json
