### ISSUE TITLE
UWP. Unhandled exception in case of mac address with leading 0

### ISSUE THREAD

**Issue by susloparovdenis** [aritchie/bluetoothle#62]
![2017-07-30 17_27_02-bluelight windowstest debugging - microsoft visual studio](https://user-images.githubusercontent.com/5947908/28754766-88493620-754c-11e7-95cb-8340065bd108.png)

**Comment by aritchie** [comment]
Thanks for the PR and bug.  Can you please provide a MAC address where this was failing?  I haven't had an issue with this function in the current testing

**Comment by susloparovdenis** [comment]
08:66:98:D0:3B:6A
but in the address argument was the string "86698D03B6A"

**Comment by KevinBaselinesw** [comment]
I hit this problem as well.   Here is how I fixed it.  Feel free to integrate if you would like

    protected Guid GetDeviceId(string address)
        {
            string EmptyGuid = Guid.Empty.ToString();

            address = EmptyGuid.Substring(0, EmptyGuid.Length - address.Length) + address;

            var mac = address
                .Replace("BluetoothLE#BluetoothLE", String.Empty)
                .Replace(":", String.Empty)
                .Replace("-", String.Empty);

            var deviceGuid = new byte[16];
            var macBytes = Enumerable
                .Range(0, mac.Length)
                .Where(x => x % 2 == 0)
                .Select(x => Convert.ToByte(mac.Substring(x, 2), 16))
                .ToArray();

            macBytes.CopyTo(deviceGuid, 0); // 12 bytes here if off the BluetoothLEDevice
            return new Guid(deviceGuid);
        }
