### ISSUE TITLE
Cannot build Sample App for android

### ISSUE THREAD

**Issue by FrozenKiwi** [aritchie/bluetoothle#67]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] PCL
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
7.1

## Version of Library
4.0.1

## Expected Behaviour
Sample App should Build and deploy to Android

## Actual Behavior
Download repository, and compile.

Sample App throws errors on build:  
> Package 'reactiveui.7.5.0-alpha0027' is not found on source 'https://api.nuget.org/v3/index.json'

On Deploy:
> Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'ReactiveUI, Version=8.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?

Oddly - although NuGet insists there is no version reactive 7.5 (or 8) on it's servers, it somehow managed to acquire a reference to v8.0.0-alpha0034 in Sample, and the UWP version of the sample works (mostly, still won't connect to my Bluno, but at least it runs).

I can't find any reference to publicly available packages on ReactiveUI boards, how/where do I find this dependency?  Should I just build it myself?

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible
Contact GitHub

**Comment by aritchie** [comment]
Please make an attempt to read through the issues before posting things like this.  This has already been answered in #59
