### ISSUE TITLE
Cannot see IsMtuRequestAvailable and RequestMtu.

### ISSUE THREAD

**Issue by oOGabsOo** [aritchie/bluetoothle#7]
Hello,

I just installed the package with nuget. But when I receive a ScanResult and try to access the device in order to try a RequestMtu, the methods are not available in my form project. 

` 
BleAdapter.Current.Scan().Subscribe(scanResult => {
                scanResult.Device.Connect();
                scanResult.Device.IsMtuRequestAvailable
            });`

What am i missing here? I saw in the sample in the repository that you are actually accessing it without any trouble in "DeviceViewModel" : 

` 
 this.RequestMtu = ReactiveCommand.CreateFromTask(
                async x =>
                {
                    if (!this.device.IsMtuRequestAvailable)
                    {
                        this.Dialogs.Alert("MTU Request not supported on this platform");
                    }
` 
Thank you in advance for your help.

Cheers,

**Comment by aritchie** [comment]
what nuget package version are you using?

**Comment by oOGabsOo** [comment]
Ok solved ;) It was a missing update of the package ;)
