### ISSUE TITLE
Does not build cleanly - crashes on android

### ISSUE THREAD

**Issue by KevinBaselinesw** [aritchie/bluetoothle#70]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] PCL
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Android 6.0
Ios (N/A)
Windows 10

## Version of Library
Whatever is the latest from GitHub on Aug31,2017

## Expected Behaviour

package should build cleanly using VS2017.

## Actual Behavior

Package does not build because:

Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project Samples.macOS: Unable to find version '7.5.0-alpha0027' of package 'reactiveui'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'reactiveui.7.5.0-alpha0027' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'reactiveui.7.5.0-alpha0027' is not found on source 'https://api.nuget.org/v3/index.json'.
.				
Can fix this error by changing packages.config to use v7.4.

However, it seems to throw an unhandled exception on Android immediately after launch.  This is Android 6.0.  There is no usable information in the exception.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible
Contact GitHub

**Comment by aritchie** [comment]
I'm using an alpha version of reactiveui for the .NET standard support.  This has been answered in other bugs.  Samples are not part of the defect train here.
