### ISSUE TITLE
iTunes Review : iPhone and iPad running iOS 11 on Wi-Fi connected to an IPv6 network.

### ISSUE THREAD

**Issue by Enoges** [aritchie/bluetoothle#73]
- [] iOS

## Version of OS(s) listed above with issue
10.3.3 & 11

## Version of Library
4.0.0 

## Expected Behaviour
Detect the device with bluetooth connected with an wifi IPv6 network.

## Actual Behavior
Recently an app who used bluetoothle to detect a BLE button push was rejected from apple review system with that explanation.

> Guideline 2.1 - Performance - App Completeness
> We discovered one or more bugs in your app when reviewed on iPhone and iPad running iOS 11 on Wi-Fi connected to an IPv6 network.
>
>Specifically, we found the app was never able to find the bluetooth button. 

In our tests with iOS 10.3.3 and below, we can detect the device without problem, but apple said it isn't.
Appearly the problem comes from wifi ipv6 network. ¿Did you know about that issue?¿Is it easy resolution?

Thanks for your time.

**Comment by aritchie** [comment]
I’m not sure how this has anything to do with this library?  Ble has nothing to do with wifi.  

With the detection of Ble devices, my tests all seem to be working with iOS 11
