### ISSUE TITLE
Can't open solution once NuGet package installed

### ISSUE THREAD

**Issue by esseivan** [aritchie/bluetoothle#74]
I installed the NuGet package Plugin.BluetoothLE 5.0.0 on the project.
Once I closed and reoppened VS2017, the solution takes a very long time (5-10 minutes) to open or it even doesn't.

Sometimes more lucky, it opens without any problem but quite randomly.

I used a blank new app from Xamarin and just imported the Plugin.BluetoothLE 5.0.0 package without any other modification.

Any idea to solve it ?

**Comment by aritchie** [comment]
Unfortunately, this sits outside of anything to do with this library.  The nuget package isn't doing anything magically.  However, you should note that this library is based on .NET standard (1.x), not PCL.  The default Xamarin Forms template is still based on the old PCL model.  That may be having an impact on what you're seeing.

Please use the issue template in the future as it saves me having to ask the usual questions.

**Comment by esseivan** [comment]
And another thing, just after installing the package, it shows an error saying that System.Runtime.InteropServices.WindowsRuntime is imported two times but when I delete the one in references, more errors shows up

**Comment by aritchie** [comment]
Please read my previous message before posting further.  It is definitely related to .NET standard.

**Comment by esseivan** [comment]
What should I change to get this working ? Shouldn't .NET standard work with PCL ?

**Comment by aritchie** [comment]
PCL's will work in .NET standard.  The other way around is hit or miss depending on the profile matchups.  I was suggest taking a look at a few articles on xamarin forms & .net standard to see what's involved.

**Comment by esseivan** [comment]
And should I download the source code here to create a project using your library or just importing the nuget package is enough

**Comment by aritchie** [comment]
nuget is enough
