### ISSUE TITLE
Simultaneous connections limit

### ISSUE THREAD

**Issue by wmcainsh** [aritchie/bluetoothle#81]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS

## Version of OS(s) listed above with issue
8.2

## Version of Library
3.1.1 (Can't upgrade to 5.0 atm as other plugins are not compatible with reactiveui v8)

## Expected Behaviour
Connect to multiple devices simultaneously

## Actual Behavior
Before upgrading to iOS 8.2 I was able to connect to approx 6 devices at the same time before my app froze / crashed.
Now with iOS 8.2, 3 devices appears to be the limit.

Is there a limit to the number of devices that can be connected to and is there a pattern / strategy for communicating with multiple devices simultaneously? I anticipate a maximum of around 30 devices at any one time.

**Comment by aritchie** [comment]
There is no limit imposed by this library
