### ISSUE TITLE
Android nuget package reference wrong lib

### ISSUE THREAD

**Issue by rmenezes** [aritchie/bluetoothle#93]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Android 7.1.1

## Version of Library
5.2.2

## Expected Behaviour
Reference Lib/MonoAndroid80

## Actual Behavior
When I try to install the package from nuget on my Android application the version that is referenced in my csproject is the netstandard2.0 version instead of MonoAndroid80. 
![print](https://user-images.githubusercontent.com/1154679/33241493-5161ee4a-d2ad-11e7-9d4c-fd8d8f691c95.PNG)

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Works fine for me.  Make sure your android target is set to 8.0.
